const defaultEmoji = {
    "people": {
        "name": "People",
        "icon": "😀",
        "emoji": {
            "grinning face": "😀",
            "grinning face with big eyes": "😃",
            "grinning face with smiling eyes": "😄",
            "beaming face with smiling eyes": "😁",
            "grinning squinting face": "😆",
            "grinning face with sweat": "😅",
            "rolling on the floor laughing": "🤣",
            "face with tears of joy": "😂",
            "slightly smiling face": "🙂",
            "winking face": "😉",
            "smiling face with smiling eyes": "😊",
            "smiling face with halo, innocent": "😇",
            "smiling face with hearts": "🥰",
            "smiling face with heart-eyes": "😍",
            "star-struck": "🤩",
            "face blowing a kiss": "😘",
            "kissing face": "😗",
            "smiling face": "☺️",
            "kissing face with closed eyes": "😚",
            "kissing face with smiling eyes": "😙",
            "smiling face with tear": "🥲",
            "smirking face": "😏",
            "face savoring food": "😋",
            "face with tongue": "😛",
            "winking face with tongue": "😜",
            "zany face": "🤪",
            "squinting face with tongue": "😝",
            "smiling face with open hands": "🤗",
            "face with hand over mouth": "🤭",
            "face with open eyes and hand over mouth": "🫢",
            "face with peeking eye": "🫣",
            "shushing face": "🤫",
            "thinking face": "🤔",
            "saluting face": "🫡",
            "drooling face": "🤤",
            "cowboy hat face": "🤠",
            "partying face": "🥳",
            "disguised face": "🥸",
            "smiling face with sunglasses": "😎",
            "nerd face": "🤓",
            "face with monocle": "🧐",
            "upside-down face": "🙃",
            "melting face": "🫠",
            "zipper-mouth face": "🤐",
            "face with raised eyebrow": "🤨",
            "neutral face": "😐",
            "expressionless face": "😑",
            "face without mouth": "😶",
            "dotted line face": "🫥",
            "face in clouds": "😶‍🌫️",
            "unamused face": "😒",
            "face with rolling eyes": "🙄",
            "grimacing face": "😬",
            "face exhaling": "😮‍💨",
            "lying face": "🤥",
            "shaking face": "🫨",
            "relieved face": "😌",
            "pensive face": "😔",
            "sleepy face": "😪",
            "sleeping face": "😴",
            "face with medical mask": "😷",
            "face with thermometer": "🤒",
            "face with head-bandage": "🤕",
            "nauseated face": "🤢",
            "face vomiting": "🤮",
            "sneezing face": "🤧",
            "hot face": "🥵",
            "cold face": "🥶",
            "woozy face": "🥴",
            "face with crossed-out eyes": "😵",
            "face with spiral eyes": "😵‍💫",
            "exploding head": "🤯",
            "yawning face": "🥱",
            "confused face": "😕",
            "face with diagonal mouth": "🫤",
            "worried face": "😟",
            "slightly frowning face": "🙁",
            "frowning face": "☹️",
            "face with open mouth": "😮",
            "hushed face": "😯",
            "astonished face": "😲",
            "flushed face": "😳",
            "pleading face": "🥺",
            "face holding back tears": "🥹",
            "frowning face with open mouth": "😦",
            "anguished face": "😧",
            "fearful face": "😨",
            "anxious face with sweat": "😰",
            "sad but relieved face": "😥",
            "crying face": "😢",
            "sobbing face": "😭",
            "face screaming in fear": "😱",
            "confounded face": "😖",
            "persevering face": "😣",
            "disappointed face": "😞",
            "downcast face with sweat": "😓",
            "weary face": "😩",
            "tired face": "😫",
            "face with steam from nose": "😤",
            "enraged face": "😡",
            "angry face": "😠",
            "face with symbols on mouth": "🤬",
            "angry face with horns": "👿",
            "devil smiling": "😈",
            "angry devil": "👿",
            "skull": "💀",
            "skull and crossbones": "☠️",
            "pile of poo": "💩",
            "clown face": "🤡",
            "ogre": "👹",
            "goblin": "👺",
            "ghost": "👻",
            "alien": "👽",
            "space invader": "👾",
            "robot": "🤖",
            "grinning cat": "😺",
            "grinning cat with smiling eyes": "😸",
            "cat with tears of joy": "😹",
            "smiling cat with heart-eyes": "😻",
            "cat with wry smile": "😼",
            "kissing cat": "😽",
            "weary cat": "🙀",
            "crying cat": "😿",
            "pouting cat": "😾",
            "see-no-evil monkey": "🙈",
            "hear-no-evil monkey": "🙉",
            "speak-no-evil monkey": "🙊",
            "boy": "👦",
            "girl": "👧",
            "man": "👨",
            "woman": "👩",
            "old man": "👴",
            "old woman": "👵",
            "baby": "👶",
            "baby angel": "👼",
            "man health worker": "👨‍⚕️",
            "woman health worker": "👩‍⚕️",
            "man student": "👨‍🎓",
            "woman student": "👩‍🎓",
            "man teacher": "👨‍🏫",
            "woman teacher": "👩‍🏫",
            "man judge": "👨‍⚖️",
            "woman judge": "👩‍⚖️",
            "man farmer": "👨‍🌾",
            "woman farmer": "👩‍🌾",
            "man cook": "👨‍🍳",
            "woman cook": "👩‍🍳",
            "man mechanic": "👨‍🔧",
            "woman mechanic": "👩‍🔧",
            "man factory worker": "👨‍🏭",
            "woman factory worker": "👩‍🏭",
            "man office worker": "👨‍💼",
            "woman office worker": "👩‍💼",
            "man scientist": "👨‍🔬",
            "woman scientist": "👩‍🔬",
            "man technologist": "👨‍💻",
            "woman technologist": "👩‍💻",
            "man singer": "👨‍🎤",
            "woman singer": "👩‍🎤",
            "man artist": "👨‍🎨",
            "woman artist": "👩‍🎨",
            "man pilot": "👨‍✈️",
            "woman pilot": "👩‍✈️",
            "man astronaut": "👨‍🚀",
            "woman astronaut": "👩‍🚀",
            "man firefighter": "👨‍🚒",
            "woman firefighter": "👩‍🚒",
            "police officer": "👮",
            "man police officer": "👮‍♂️",
            "woman police officer": "👮‍♀️",
            "detective": "🕵️",
            "man detective": "🕵️‍♂️",
            "woman detective": "🕵️‍♀️",
            "guard": "💂",
            "man guard": "💂‍♂️",
            "woman guard": "💂‍♀️",
            "construction worker": "👷",
            "man construction worker": "👷‍♂️",
            "woman construction worker": "👷‍♀️",
            "person wearing turban": "👳",
            "man wearing turban": "👳‍♂️",
            "woman wearing turban": "👳‍♀️",
            "blond-haired person": "👱",
            "blond-haired man": "👱‍♂️",
            "blond-haired woman": "👱‍♀️",
            "Santa Claus": "🎅",
            "Mrs. Claus": "🤶",
            "princess": "👸",
            "prince": "🤴",
            "bride with veil": "👰",
            "man in tuxedo": "🤵",
            "pregnant woman": "🤰",
            "man with Chinese cap": "👲",
            "person frowning": "🙍",
            "man frowning": "🙍‍♂️",
            "woman frowning": "🙍‍♀️",
            "person pouting": "🙎",
            "man pouting": "🙎‍♂️",
            "woman pouting": "🙎‍♀️",
            "person gesturing NO": "🙅",
            "man gesturing NO": "🙅‍♂️",
            "woman gesturing NO": "🙅‍♀️",
            "person gesturing OK": "🙆",
            "man gesturing OK": "🙆‍♂️",
            "woman gesturing OK": "🙆‍♀️",
            "person tipping hand": "💁",
            "man tipping hand": "💁‍♂️",
            "woman tipping hand": "💁‍♀️",
            "person raising hand": "🙋",
            "man raising hand": "🙋‍♂️",
            "woman raising hand": "🙋‍♀️",
            "person bowing": "🙇",
            "man bowing": "🙇‍♂️",
            "woman bowing": "🙇‍♀️",
            "person facepalming": "🤦",
            "man facepalming": "🤦‍♂️",
            "woman facepalming": "🤦‍♀️",
            "person shrugging": "🤷",
            "man shrugging": "🤷‍♂️",
            "woman shrugging": "🤷‍♀️",
            "person getting massage": "💆",
            "man getting massage": "💆‍♂️",
            "woman getting massage": "💆‍♀️",
            "person getting haircut": "💇",
            "man getting haircut": "💇‍♂️",
            "woman getting haircut": "💇‍♀️",
            "deaf person": "🧏",
            "person walking": "🚶",
            "man walking": "🚶‍♂️",
            "woman walking": "🚶‍♀️",
            "person running": "🏃",
            "man running": "🏃‍♂️",
            "woman running": "🏃‍♀️",
            "woman dancing": "💃",
            "man dancing": "🕺",
            "people with bunny ears partying": "👯",
            "men with bunny ears partying": "👯‍♂️",
            "women with bunny ears partying": "👯‍♀️",
            "man in business suit levitating": "🕴️",
            "speaking head": "🗣️",
            "bust in silhouette": "👤",
            "busts in silhouette": "👥",
            "person fencing": "🤺",
            "horse racing": "🏇",
            "skier": "⛷️",
            "snowboarder": "🏂",
            "person golfing": "🏌️",
            "man golfing": "🏌️‍♂️",
            "woman golfing": "🏌️‍♀️",
            "person surfing": "🏄",
            "man surfing": "🏄‍♂️",
            "woman surfing": "🏄‍♀️",
            "person rowing boat": "🚣",
            "man rowing boat": "🚣‍♂️",
            "woman rowing boat": "🚣‍♀️",
            "person swimming": "🏊",
            "man swimming": "🏊‍♂️",
            "woman swimming": "🏊‍♀️",
            "person bouncing ball": "⛹️",
            "man bouncing ball": "⛹️‍♂️",
            "woman bouncing ball": "⛹️‍♀️",
            "person lifting weights": "🏋️",
            "man lifting weights": "🏋️‍♂️",
            "woman lifting weights": "🏋️‍♀️",
            "person biking": "🚴",
            "man biking": "🚴‍♂️",
            "woman biking": "🚴‍♀️",
            "person mountain biking": "🚵",
            "man mountain biking": "🚵‍♂️",
            "woman mountain biking": "🚵‍♀️",
            "racing car": "🏎️",
            "motorcycle": "🏍️",
            "person cartwheeling": "🤸",
            "man cartwheeling": "🤸‍♂️",
            "woman cartwheeling": "🤸‍♀️",
            "people wrestling": "🤼",
            "men wrestling": "🤼‍♂️",
            "women wrestling": "🤼‍♀️",
            "person playing water polo": "🤽",
            "man playing water polo": "🤽‍♂️",
            "woman playing water polo": "🤽‍♀️",
            "person playing handball": "🤾",
            "man playing handball": "🤾‍♂️",
            "woman playing handball": "🤾‍♀️",
            "person juggling": "🤹",
            "man juggling": "🤹‍♂️",
            "woman juggling": "🤹‍♀️",
            "man and woman holding hands": "👫",
            "two men holding hands": "👬",
            "two women holding hands": "👭",
            "kiss": "💏",
            "couple with heart": "💑",
            "family": "👪",
            "flexed biceps": "💪",
            "selfie": "🤳",
            "backhand index pointing at screen": "🫵",
            "backhand index pointing left": "👈",
            "backhand index pointing right": "👉",
            "index pointing up": "☝️",
            "backhand index pointing up": "👆",
            "middle finger": "🖕",
            "backhand index pointing down": "👇",
            "victory hand": "✌️",
            "crossed fingers": "🤞",
            "vulcan salute": "🖖",
            "sign of the horns": "🤘",
            "call me hand": "🤙",
            "raised hand with fingers splayed": "🖐️",
            "raised hand": "✋",
            "OK hand": "👌",
            "thumbs up": "👍",
            "thumbs down": "👎",
            "raised fist": "✊",
            "oncoming fist": "👊",
            "left-facing fist": "🤛",
            "right-facing fist": "🤜",
            "raised back of hand": "🤚",
            "waving hand": "👋",
            "clapping hands": "👏",
            "writing hand": "✍️",
            "open hands": "👐",
            "raising hands": "🙌",
            "folded hands, pray": "🙏",
            "handshake": "🤝",
            "nail polish": "💅",
            "ear": "👂",
            "nose": "👃",
            "footprints": "👣",
            "eyes": "👀",
            "eye": "👁️",
            "eye in speech bubble": "👁️‍🗨️",
            "tongue": "👅",
            "mouth": "👄",
            "kiss mark": "💋",
            "glasses": "👓",
            "sunglasses": "🕶️",
            "necktie": "👔",
            "t-shirt": "👕",
            "jeans": "👖",
            "dress": "👗",
            "kimono": "👘",
            "bikini": "👙",
            "woman's clothes": "👚",
            "purse": "👛",
            "handbag": "👜",
            "clutch bag": "👝",
            "shopping bags": "🛍️",
            "school backpack": "🎒",
            "man's shoe": "👞",
            "running shoe": "👟",
            "high-heeled shoe": "👠",
            "woman's sandal": "👡",
            "woman's boot": "👢",
            "crown": "👑",
            "woman's hat": "👒",
            "top hat": "🎩",
            "graduation cap": "🎓",
            "rescue worker's helmet": "⛑️",
            "prayer beads": "📿",
            "lipstick": "💄",
            "ring": "💍",
            "gem stone": "💎",
        },
    },
    "animals": {
        "name": "Animals & Nature",
        "icon": "😺",
        "emoji": {
            "monkey face": "🐵",
            "monkey": "🐒",
            "gorilla": "🦍",
            "dog face": "🐶",
            "dog": "🐕",
            "poodle": "🐩",
            "wolf face": "🐺",
            "fox face": "🦊",
            "cat face": "🐱",
            "cat": "🐈",
            "lion face": "🦁",
            "tiger face": "🐯",
            "tiger": "🐅",
            "leopard": "🐆",
            "horse face": "🐴",
            "horse": "🐎",
            "deer": "🦌",
            "unicorn face": "🦄",
            "cow face": "🐮",
            "ox": "🐂",
            "water buffalo": "🐃",
            "cow": "🐄",
            "pig face": "🐷",
            "pig": "🐖",
            "boar": "🐗",
            "pig nose": "🐽",
            "ram": "🐏",
            "sheep": "🐑",
            "goat": "🐐",
            "camel": "🐪",
            "two-hump camel": "🐫",
            "elephant": "🐘",
            "rhinoceros": "🦏",
            "mouse face": "🐭",
            "mouse": "🐁",
            "rat": "🐀",
            "hamster face": "🐹",
            "rabbit face": "🐰",
            "rabbit": "🐇",
            "chipmunk": "🐿️",
            "bat": "🦇",
            "bear face": "🐻",
            "koala": "🐨",
            "panda face": "🐼",
            "paw prints": "🐾",
            "turkey": "🦃",
            "chicken": "🐔",
            "rooster": "🐓",
            "hatching chick": "🐣",
            "baby chick": "🐤",
            "front-facing baby chick": "🐥",
            "bird": "🐦",
            "penguin": "🐧",
            "dove": "🕊️",
            "eagle": "🦅",
            "duck": "🦆",
            "owl": "🦉",
            "frog face": "🐸",
            "crocodile": "🐊",
            "turtle": "🐢",
            "lizard": "🦎",
            "snake": "🐍",
            "dragon face": "🐲",
            "dragon": "🐉",
            "spouting whale": "🐳",
            "whale": "🐋",
            "dolphin": "🐬",
            "fish": "🐟",
            "tropical fish": "🐠",
            "blowfish": "🐡",
            "shark": "🦈",
            "octopus": "🐙",
            "spiral shell": "🐚",
            "crab": "🦀",
            "shrimp": "🦐",
            "squid": "🦑",
            "butterfly": "🦋",
            "snail": "🐌",
            "bug": "🐛",
            "ant": "🐜",
            "honeybee": "🐝",
            "lady beetle": "🐞",
            "spider": "🕷️",
            "spider web": "🕸️",
            "scorpion": "🦂",
            "bouquet": "💐",
            "cherry blossom": "🌸",
            "white flower": "💮",
            "rosette": "🏵️",
            "rose": "🌹",
            "wilted flower": "🥀",
            "hibiscus": "🌺",
            "sunflower": "🌻",
            "blossom": "🌼",
            "tulip": "🌷",
            "seedling": "🌱",
            "evergreen tree": "🌲",
            "deciduous tree": "🌳",
            "palm tree": "🌴",
            "cactus": "🌵",
            "sheaf of rice": "🌾",
            "herb": "🌿",
            "shamrock": "☘️",
            "four leaf clover": "🍀",
            "maple leaf": "🍁",
            "fallen leaf": "🍂",
            "leaf fluttering in wind": "🍃",
            "new moon": "🌑",
            "waxing crescent moon": "🌒",
            "first quarter moon": "🌓",
            "waxing gibbous moon": "🌔",
            "full moon": "🌕",
            "waning gibbous moon": "🌖",
            "last quarter moon": "🌗",
            "waning crescent moon": "🌘",
            "crescent moon": "🌙",
            "new moon face": "🌚",
            "first quarter moon with face": "🌛",
            "last quarter moon with face": "🌜",
            "full moon with face": "🌝",
            "thermometer": "🌡️",
            "sun": "☀️",
            "sun with face": "🌞",
            "white medium star": "⭐",
            "planet": "🪐",
            "glowing star": "🌟",
            "shooting star": "🌠",
            "cloud": "☁️",
            "sun behind cloud": "⛅",
            "cloud with lightning and rain": "⛈️",
            "sun behind small cloud": "🌤️",
            "sun behind large cloud": "🌥️",
            "sun behind rain cloud": "🌦️",
            "cloud with rain": "🌧️",
            "cloud with snow": "🌨️",
            "cloud with lightning": "🌩️",
            "tornado": "🌪️",
            "fog": "🌫️",
            "wind face": "🌬️",
            "cyclone": "🌀",
            "rainbow": "🌈",
            "closed umbrella": "🌂",
            "umbrella": "☂️",
            "umbrella with rain drops": "☔",
            "umbrella on ground": "⛱️",
            "high voltage": "⚡",
            "snowflake": "❄️",
            "snowman": "☃️",
            "snowman without snow": "⛄",
            "comet": "☄️",
            "fire": "🔥",
            "droplet": "💧",
            "water wave": "🌊",
            "sweat droplets": "💦",
            "dashing away": "💨",
            "dizzy": "💫",
        },
    },
    "food": {
        "name": "Food & Drink",
        "icon": "🍎",
        "emoji": {
            "grapes": "🍇",
            "melon": "🍈",
            "watermelon": "🍉",
            "tangerine, orange": "🍊",
            "lemon": "🍋",
            "banana": "🍌",
            "pineapple": "🍍",
            "red apple": "🍎",
            "green apple": "🍏",
            "pear": "🍐",
            "peach": "🍑",
            "cherries": "🍒",
            "strawberry": "🍓",
            "kiwi fruit": "🥝",
            "tomato": "🍅",
            "avocado": "🥑",
            "eggplant": "🍆",
            "potato": "🥔",
            "carrot": "🥕",
            "ear of corn": "🌽",
            "hot pepper": "🌶️",
            "cucumber": "🥒",
            "mushroom": "🍄",
            "peanuts": "🥜",
            "chestnut": "🌰",
            "bread": "🍞",
            "croissant": "🥐",
            "baguette bread": "🥖",
            "pancakes": "🥞",
            "cheese wedge": "🧀",
            "meat on bone": "🍖",
            "poultry leg": "🍗",
            "bacon": "🥓",
            "hamburger": "🍔",
            "french fries": "🍟",
            "pizza": "🍕",
            "hot dog": "🌭",
            "taco": "🌮",
            "burrito": "🌯",
            "stuffed flatbread": "🥙",
            "egg": "🥚",
            "cooking": "🍳",
            "shallow pan of food": "🥘",
            "pot of food": "🍲",
            "green salad": "🥗",
            "popcorn": "🍿",
            "bento box": "🍱",
            "rice cracker": "🍘",
            "rice ball": "🍙",
            "cooked rice": "🍚",
            "curry rice": "🍛",
            "steaming bowl": "🍜",
            "spaghetti": "🍝",
            "roasted sweet potato": "🍠",
            "oden": "🍢",
            "sushi": "🍣",
            "fried shrimp": "🍤",
            "fish cake with swirl": "🍥",
            "dango": "🍡",
            "soft ice cream": "🍦",
            "shaved ice": "🍧",
            "ice cream": "🍨",
            "doughnut": "🍩",
            "cookie": "🍪",
            "birthday cake": "🎂",
            "shortcake": "🍰",
            "chocolate bar": "🍫",
            "candy": "🍬",
            "lollipop": "🍭",
            "custard": "🍮",
            "honey pot": "🍯",
            "baby bottle": "🍼",
            "glass of milk": "🥛",
            "hot beverage": "☕",
            "teacup without handle": "🍵",
            "sake": "🍶",
            "bottle with popping cork": "🍾",
            "wine glass": "🍷",
            "cocktail glass": "🍸",
            "tropical drink": "🍹",
            "beer mug": "🍺",
            "clinking beer mugs": "🍻",
            "clinking glasses": "🥂",
            "tumbler glass": "🥃",
            "fork and knife with plate": "🍽️",
            "fork and knife": "🍴",
            "spoon": "🥄",
            "kitchen knife": "🔪",
            "amphora": "🏺",
        },
    },
    "travel": {
        "name": "Travel",
        "icon": "🏠",
        "emoji": {
            "globe showing Europe-Africa": "🌍",
            "globe showing Americas": "🌎",
            "globe showing Asia-Australia": "🌏",
            "globe with meridians": "🌐",
            "world map": "🗺️",
            "map of Japan": "🗾",
            "snow-capped mountain": "🏔️",
            "mountain": "⛰️",
            "volcano": "🌋",
            "mount fuji": "🗻",
            "camping": "🏕️",
            "beach with umbrella": "🏖️",
            "desert": "🏜️",
            "desert island": "🏝️",
            "national park": "🏞️",
            "stadium": "🏟️",
            "classical building": "🏛️",
            "building construction": "🏗️",
            "house": "🏘️",
            "cityscape": "🏙️",
            "derelict house": "🏚️",
            "house": "🏠",
            "house with garden": "🏡",
            "office building": "🏢",
            "Japanese post office": "🏣",
            "post office": "🏤",
            "hospital": "🏥",
            "bank": "🏦",
            "hotel": "🏨",
            "love hotel": "🏩",
            "convenience store": "🏪",
            "school": "🏫",
            "department store": "🏬",
            "factory": "🏭",
            "Japanese castle": "🏯",
            "castle": "🏰",
            "wedding": "💒",
            "Tokyo tower": "🗼",
            "Statue of Liberty": "🗽",
            "church": "⛪",
            "mosque": "🕌",
            "synagogue": "🕍",
            "shinto shrine": "⛩️",
            "kaaba": "🕋",
            "fountain": "⛲",
            "tent": "⛺",
            "foggy": "🌁",
            "night with stars": "🌃",
            "sunrise over mountains": "🌄",
            "sunrise": "🌅",
            "cityscape at dusk": "🌆",
            "sunset": "🌇",
            "bridge at night": "🌉",
            "hot springs": "♨️",
            "milky way": "🌌",
            "carousel horse": "🎠",
            "ferris wheel": "🎡",
            "roller coaster": "🎢",
            "barber pole": "💈",
            "circus tent": "🎪",
            "performing arts": "🎭",
            "framed picture": "🖼️",
            "artist palette": "🎨",
            "slot machine": "🎰",
            "locomotive": "🚂",
            "railway car": "🚃",
            "high-speed train": "🚄",
            "high-speed train with bullet nose": "🚅",
            "train": "🚆",
            "metro": "🚇",
            "light rail": "🚈",
            "station": "🚉",
            "tram": "🚊",
            "monorail": "🚝",
            "mountain railway": "🚞",
            "tram car": "🚋",
            "bus": "🚌",
            "oncoming bus": "🚍",
            "trolleybus": "🚎",
            "minibus": "🚐",
            "ambulance": "🚑",
            "fire engine": "🚒",
            "police car": "🚓",
            "oncoming police car": "🚔",
            "taxi": "🚕",
            "oncoming taxi": "🚖",
            "automobile": "🚗",
            "oncoming automobile": "🚘",
            "sport utility vehicle": "🚙",
            "delivery truck": "🚚",
            "articulated lorry": "🚛",
            "tractor": "🚜",
            "bicycle": "🚲",
            "kick scooter": "🛴",
            "motor scooter": "🛵",
            "bus stop": "🚏",
            "motorway": "🛣️",
            "railway track": "🛤️",
            "fuel pump": "⛽",
            "police car light": "🚨",
            "horizontal traffic light": "🚥",
            "vertical traffic light": "🚦",
            "construction": "🚧",
            "stop sign": "🛑",
            "anchor": "⚓",
            "sailboat": "⛵",
            "canoe": "🛶",
            "speedboat": "🚤",
            "passenger ship": "🛳️",
            "ferry": "⛴️",
            "motor boat": "🛥️",
            "ship": "🚢",
            "airplane": "✈️",
            "small airplane": "🛩️",
            "airplane departure": "🛫",
            "airplane arrival": "🛬",
            "seat": "💺",
            "helicopter": "🚁",
            "suspension railway": "🚟",
            "mountain cableway": "🚠",
            "aerial tramway": "🚡",
            "rocket": "🚀",
            "satellite": "🛰️",
            "bellhop bell": "🛎️",
            "door": "🚪",
            "person in bed": "🛌",
            "bed": "🛏️",
            "couch and lamp": "🛋️",
            "toilet": "🚽",
            "shower": "🚿",
            "person taking bath": "🛀",
            "bathtub": "🛁",
            "hourglass": "⌛",
            "hourglass with flowing sand": "⏳",
            "watch": "⌚",
            "alarm clock": "⏰",
            "stopwatch": "⏱️",
            "timer clock": "⏲️",
            "mantelpiece clock": "🕰️",
        },
    },
    "activities": {
        "name": "Activities",
        "icon": "⚽",
        "emoji": {
            "jack-o-lantern": "🎃",
            "Christmas tree": "🎄",
            "fireworks": "🎆",
            "sparkler": "🎇",
            "sparkles": "✨",
            "balloon": "🎈",
            "party popper": "🎉",
            "confetti ball": "🎊",
            "tanabata tree": "🎋",
            "pine decoration": "🎍",
            "Japanese dolls": "🎎",
            "carp streamer": "🎏",
            "wind chime": "🎐",
            "moon viewing ceremony": "🎑",
            "ribbon": "🎀",
            "wrapped gift": "🎁",
            "reminder ribbon": "🎗️",
            "admission tickets": "🎟️",
            "ticket": "🎫",
            "military medal": "🎖️",
            "trophy": "🏆",
            "sports medal": "🏅",
            "1st place medal": "🥇",
            "2nd place medal": "🥈",
            "3rd place medal": "🥉",
            "soccer ball": "⚽",
            "baseball": "⚾",
            "basketball": "🏀",
            "volleyball": "🏐",
            "american football": "🏈",
            "rugby football": "🏉",
            "tennis": "🎾",
            "pool 8 ball": "🎱",
            "bowling": "🎳",
            "cricket": "🏏",
            "field hockey": "🏑",
            "ice hockey": "🏒",
            "ping pong": "🏓",
            "badminton": "🏸",
            "boxing glove": "🥊",
            "martial arts uniform": "🥋",
            "goal net": "🥅",
            "direct hit": "🎯",
            "flag in hole": "⛳",
            "ice skate": "⛸️",
            "fishing pole": "🎣",
            "running shirt": "🎽",
            "skis": "🎿",
            "video game": "🎮",
            "joystick": "🕹️",
            "game die": "🎲",
            "spade suit": "♠️",
            "heart suit": "♥️",
            "diamond suit": "♦️",
            "club suit": "♣️",
            "joker": "🃏",
            "mahjong red dragon": "🀄",
            "flower playing cards": "🎴",
        },
    },
    "objects": {
        "name": "Objects",
        "icon": "📃",
        "emoji": {
            "loudspeaker": "📢",
            "megaphone": "📣",
            "postal horn": "📯",
            "bell": "🔔",
            "bell with slash": "🔕",
            "musical score": "🎼",
            "musical note": "🎵",
            "musical notes": "🎶",
            "studio microphone": "🎙️",
            "level slider": "🎚️",
            "control knobs": "🎛️",
            "microphone": "🎤",
            "headphone": "🎧",
            "radio": "📻",
            "saxophone": "🎷",
            "guitar": "🎸",
            "musical keyboard": "🎹",
            "trumpet": "🎺",
            "violin": "🎻",
            "drum": "🥁",
            "mobile phone": "📱",
            "mobile phone with arrow": "📲",
            "telephone": "☎️",
            "telephone receiver": "📞",
            "pager": "📟",
            "fax machine": "📠",
            "battery": "🔋",
            "electric plug": "🔌",
            "laptop computer": "💻",
            "desktop computer": "🖥️",
            "printer": "🖨️",
            "keyboard": "⌨️",
            "computer mouse": "🖱️",
            "trackball": "🖲️",
            "computer disk": "💽",
            "floppy disk": "💾",
            "optical disk": "💿",
            "dvd": "📀",
            "movie camera": "🎥",
            "film frames": "🎞️",
            "film projector": "📽️",
            "clapper board": "🎬",
            "television": "📺",
            "camera": "📷",
            "camera with flash": "📸",
            "video camera": "📹",
            "videocassette": "📼",
            "left-pointing magnifying glass": "🔍",
            "right-pointing magnifying glass": "🔎",
            "microscope": "🔬",
            "telescope": "🔭",
            "satellite antenna": "📡",
            "candle": "🕯️",
            "light bulb": "💡",
            "flashlight": "🔦",
            "red paper lantern": "🏮",
            "notebook with decorative cover": "📔",
            "closed book": "📕",
            "open book": "📖",
            "green book": "📗",
            "blue book": "📘",
            "orange book": "📙",
            "books": "📚",
            "notebook": "📓",
            "ledger": "📒",
            "page with curl": "📃",
            "scroll": "📜",
            "page facing up": "📄",
            "newspaper": "📰",
            "rolled-up newspaper": "🗞️",
            "bookmark tabs": "📑",
            "bookmark": "🔖",
            "label": "🏷️",
            "money bag": "💰",
            "yen banknote": "💴",
            "dollar banknote": "💵",
            "euro banknote": "💶",
            "pound banknote": "💷",
            "money with wings": "💸",
            "credit card": "💳",
            "chart increasing with yen": "💹",
            "currency exchange": "💱",
            "heavy dollar sign": "💲",
            "envelope": "✉️",
            "e-mail": "📧",
            "love letter": "💌",
            "incoming envelope": "📨",
            "envelope with arrow": "📩",
            "outbox tray": "📤",
            "inbox tray": "📥",
            "package": "📦",
            "closed mailbox with raised flag": "📫",
            "closed mailbox with lowered flag": "📪",
            "open mailbox with raised flag": "📬",
            "open mailbox with lowered flag": "📭",
            "postbox": "📮",
            "ballot box with ballot": "🗳️",
            "pencil": "✏️",
            "black nib": "✒️",
            "fountain pen": "🖋️",
            "pen": "🖊️",
            "paintbrush": "🖌️",
            "crayon": "🖍️",
            "memo": "📝",
            "briefcase": "💼",
            "file folder": "📁",
            "open file folder": "📂",
            "card index dividers": "🗂️",
            "calendar": "📅",
            "tear-off calendar": "📆",
            "spiral notepad": "🗒️",
            "spiral calendar": "🗓️",
            "card index": "📇",
            "chart increasing": "📈",
            "chart decreasing": "📉",
            "bar chart": "📊",
            "clipboard": "📋",
            "pushpin": "📌",
            "round pushpin": "📍",
            "paperclip": "📎",
            "linked paperclips": "🖇️",
            "straight ruler": "📏",
            "triangular ruler": "📐",
            "scissors": "✂️",
            "card file box": "🗃️",
            "file cabinet": "🗄️",
            "wastebasket": "🗑️",
            "locked": "🔒",
            "unlocked": "🔓",
            "locked with pen": "🔏",
            "locked with key": "🔐",
            "key": "🔑",
            "old key": "🗝️",
            "hammer": "🔨",
            "pick": "⛏️",
            "hammer and pick": "⚒️",
            "hammer and wrench": "🛠️",
            "dagger": "🗡️",
            "crossed swords": "⚔️",
            "pistol": "🔫",
            "bow and arrow": "🏹",
            "shield": "🛡️",
            "wrench": "🔧",
            "nut and bolt": "🔩",
            "gear": "⚙️",
            "clamp": "🗜️",
            "alembic": "⚗️",
            "balance scale": "⚖️",
            "link": "🔗",
            "chains": "⛓️",
            "syringe": "💉",
            "pill": "💊",
            "cigarette": "🚬",
            "coffin": "⚰️",
            "funeral urn": "⚱️",
            "moai": "🗿",
            "oil drum": "🛢️",
            "crystal ball": "🔮",
            "shopping cart": "🛒",
            "zzz": "💤",
            "anger symbol": "💢",
            "bomb": "💣",
            "collision": "💥",
            "grave, tomb": "🪦",
            "hole": "🕳️",
        },
    },
    "symbols": {
        "name": "Symbols",
        "icon": "❤️",
        "emoji": {
            "red heart": "❤️",
            "orange heart": "🧡",
            "yellow heart": "💛",
            "green heart": "💚",
            "light blue heart": "🩵",
            "blue heart": "💙",
            "purple heart": "💜",
            "pink heart": "🩷",
            "brown heart": "🤎",
            "black heart": "🖤",
            "two hearts": "💕",
            "revolving hearts": "💞",
            "heart with arrow": "💘",
            "beating heart": "💓",
            "broken heart": "💔",
            "sparkling heart": "💖",
            "growing heart": "💗",
            "heart with ribbon": "💝",
            "heart decoration": "💟",
            "heavy heart exclamation": "❣️",
            "ATM sign": "🏧",
            "litter in bin sign": "🚮",
            "potable water": "🚰",
            "wheelchair symbol": "♿",
            "men's room": "🚹",
            "women's room": "🚺",
            "restroom": "🚻",
            "baby symbol": "🚼",
            "water closet": "🚾",
            "passport control": "🛂",
            "customs": "🛃",
            "baggage claim": "🛄",
            "left luggage": "🛅",
            "warning": "⚠️",
            "children crossing": "🚸",
            "no entry": "⛔",
            "prohibited": "🚫",
            "no bicycles": "🚳",
            "no smoking": "🚭",
            "no littering": "🚯",
            "non-potable water": "🚱",
            "no pedestrians": "🚷",
            "no mobile phones": "📵",
            "no one under eighteen": "🔞",
            "radioactive": "☢️",
            "biohazard": "☣️",
            "up arrow": "⬆️",
            "up-right arrow": "↗️",
            "right arrow": "➡️",
            "down-right arrow": "↘️",
            "down arrow": "⬇️",
            "down-left arrow": "↙️",
            "left arrow": "⬅️",
            "up-left arrow": "↖️",
            "up-down arrow": "↕️",
            "left-right arrow": "↔️",
            "right arrow curving left": "↩️",
            "left arrow curving right": "↪️",
            "right arrow curving up": "⤴️",
            "right arrow curving down": "⤵️",
            "clockwise vertical arrows": "🔃",
            "anticlockwise arrows button": "🔄",
            "BACK arrow": "🔙",
            "END arrow": "🔚",
            "ON! arrow": "🔛",
            "SOON arrow": "🔜",
            "TOP arrow": "🔝",
            "place of worship": "🛐",
            "atom symbol": "⚛️",
            "om": "🕉️",
            "star of David": "✡️",
            "wheel of dharma": "☸️",
            "yin yang": "☯️",
            "latin cross": "✝️",
            "orthodox cross": "☦️",
            "star and crescent": "☪️",
            "peace symbol": "☮️",
            "menorah": "🕎",
            "dotted six-pointed star": "🔯",
            "Aries": "♈",
            "Taurus": "♉",
            "Gemini": "♊",
            "Cancer": "♋",
            "Leo": "♌",
            "Virgo": "♍",
            "Libra": "♎",
            "Scorpius": "♏",
            "Sagittarius": "♐",
            "Capricorn": "♑",
            "Aquarius": "♒",
            "Pisces": "♓",
            "Ophiuchus": "⛎",
            "muted speaker": "🔇",
            "speaker low volume": "🔈",
            "speaker medium volume": "🔉",
            "speaker high volume": "🔊",
            "shuffle tracks button": "🔀",
            "repeat button": "🔁",
            "repeat single button": "🔂",
            "play button": "▶️",
            "fast-forward button": "⏩",
            "next track button": "⏭️",
            "play or pause button": "⏯️",
            "reverse button": "◀️",
            "fast reverse button": "⏪",
            "last track button": "⏮️",
            "up button": "🔼",
            "fast up button": "⏫",
            "down button": "🔽",
            "fast down button": "⏬",
            "pause button": "⏸️",
            "stop button": "⏹️",
            "record button": "⏺️",
            "eject button": "⏏️",
            "cinema": "🎦",
            "dim button": "🔅",
            "bright button": "🔆",
            "antenna bars": "📶",
            "vibration mode": "📳",
            "mobile phone off": "📴",
            "recycling symbol": "♻️",
            "name badge": "📛",
            "fleur-de-lis": "⚜️",
            "Japanese symbol for beginner": "🔰",
            "trident emblem": "🔱",
            "heavy large circle": "⭕",
            "white heavy check mark": "✅",
            "ballot box with check": "☑️",
            "heavy check mark": "✔️",
            "heavy multiplication x": "✖️",
            "cross mark": "❌",
            "cross mark button": "❎",
            "heavy plus sign": "➕",
            "female sign": "♀️",
            "male sign": "♂️",
            "medical symbol": "⚕️",
            "heavy minus sign": "➖",
            "heavy division sign": "➗",
            "curly loop": "➰",
            "double curly loop": "➿",
            "part alternation mark": "〽️",
            "eight-spoked asterisk": "✳️",
            "eight-pointed star": "✴️",
            "sparkle": "❇️",
            "double exclamation mark": "‼️",
            "exclamation question mark": "⁉️",
            "question mark": "❓",
            "white question mark": "❔",
            "white exclamation mark": "❕",
            "exclamation mark": "❗",
            "wavy dash": "〰️",
            "copyright": "©️",
            "registered": "®️",
            "trade mark": "™️",
            "keycap 0": "0️⃣",
            "keycap 1": "1️⃣",
            "keycap 2": "2️⃣",
            "keycap 3": "3️⃣",
            "keycap 4": "4️⃣",
            "keycap 5": "5️⃣",
            "keycap 6": "6️⃣",
            "keycap 7": "7️⃣",
            "keycap 8": "8️⃣",
            "keycap 9": "9️⃣",
            "keycap 10": "🔟",
            "100 points": "💯",
            "input latin uppercase": "🔠",
            "input latin lowercase": "🔡",
            "input numbers": "🔢",
            "input symbols": "🔣",
            "input latin letters": "🔤",
            "A button (blood type)": "🅰️",
            "AB button (blood type)": "🆎",
            "B button (blood type)": "🅱️",
            "CL button": "🆑",
            "COOL button": "🆒",
            "FREE button": "🆓",
            "information": "ℹ️",
            "ID button": "🆔",
            "circled M": "Ⓜ️",
            "NEW button": "🆕",
            "NG button": "🆖",
            "O button (blood type)": "🅾️",
            "OK button": "🆗",
            "P button": "🅿️",
            "SOS button": "🆘",
            "UP! button": "🆙",
            "VS button": "🆚",
            "Japanese “here” button": "🈁",
            "Japanese “service charge” button": "🈂️",
            "Japanese “monthly amount” button": "🈷️",
            "Japanese “not free of charge” button": "🈶",
            "Japanese “reserved” button": "🈯",
            "Japanese “bargain” button": "🉐",
            "Japanese “discount” button": "🈹",
            "Japanese “free of charge” button": "🈚",
            "Japanese “prohibited” button": "🈲",
            "Japanese “acceptable” button": "🉑",
            "Japanese “application” button": "🈸",
            "Japanese “passing grade” button": "🈴",
            "Japanese “vacancy” button": "🈳",
            "Japanese “congratulations” button": "㊗️",
            "Japanese “secret” button": "㊙️",
            "Japanese “open for business” button": "🈺",
            "Japanese “no vacancy” button": "🈵",
            "black small square": "▪️",
            "white small square": "▫️",
            "white medium square": "◻️",
            "black medium square": "◼️",
            "white medium-small square": "◽",
            "black medium-small square": "◾",
            "black large square": "⬛",
            "white large square": "⬜",
            "large orange diamond": "🔶",
            "large blue diamond": "🔷",
            "small orange diamond": "🔸",
            "small blue diamond": "🔹",
            "red triangle pointed up": "🔺",
            "red triangle pointed down": "🔻",
            "diamond with a dot": "💠",
            "radio button": "🔘",
            "black square button": "🔲",
            "white square button": "🔳",
            "white circle": "⚪",
            "black circle": "⚫",
            "red circle": "🔴",
            "orange circle": "🟠",
            "yellow circle": "🟡",
            "green circle": "🟢",
            "blue circle": "🔵",
            "purple circle": "🟣",
            "brown circle": "🟤",
            "speech balloon": "💬",
            "left speech bubble": "🗨️",
            "right anger bubble": "🗯️",
            "thought balloon": "💭",
            "twelve o'clock": "🕛",
            "twelve-thirty": "🕧",
            "one o'clock": "🕐",
            "one-thirty": "🕜",
            "two o'clock": "🕑",
            "two-thirty": "🕝",
            "three o'clock": "🕒",
            "three-thirty": "🕞",
            "four o'clock": "🕓",
            "four-thirty": "🕟",
            "five o'clock": "🕔",
            "five-thirty": "🕠",
            "six o'clock": "🕕",
            "six-thirty": "🕡",
            "seven o'clock": "🕖",
            "seven-thirty": "🕢",
            "eight o'clock": "🕗",
            "eight-thirty": "🕣",
            "nine o'clock": "🕘",
            "nine-thirty": "🕤",
            "ten o'clock": "🕙",
            "ten-thirty": "🕥",
            "eleven o'clock": "🕚",
            "eleven-thirty": "🕦",
        },
    },
    "flags": {
        "name": "Flags",
        "icon": "🏳️‍🌈",
        "emoji": {
            "chequered flag": "🏁",
            "triangular flag": "🚩",
            "crossed flags": "🎌",
            "black flag": "🏴",
            "white flag": "🏳️",
            "rainbow flag": "🏳️‍🌈",
            "trans flag": "🏳️‍⚧️",
            "Ascension Island": "🇦🇨",
            "Andorra": "🇦🇩",
            "United Arab Emirates": "🇦🇪",
            "Afghanistan": "🇦🇫",
            "Antigua &amp; Barbuda": "🇦🇬",
            "Anguilla": "🇦🇮",
            "Albania": "🇦🇱",
            "Armenia": "🇦🇲",
            "Angola": "🇦🇴",
            "Antarctica": "🇦🇶",
            "Argentina": "🇦🇷",
            "American Samoa": "🇦🇸",
            "Austria": "🇦🇹",
            "Australia": "🇦🇺",
            "Aruba": "🇦🇼",
            "Åland Islands": "🇦🇽",
            "Azerbaijan": "🇦🇿",
            "Bosnia &amp; Herzegovina": "🇧🇦",
            "Barbados": "🇧🇧",
            "Bangladesh": "🇧🇩",
            "Belgium": "🇧🇪",
            "Burkina Faso": "🇧🇫",
            "Bulgaria": "🇧🇬",
            "Bahrain": "🇧🇭",
            "Burundi": "🇧🇮",
            "Benin": "🇧🇯",
            "St. Barthélemy": "🇧🇱",
            "Bermuda": "🇧🇲",
            "Brunei": "🇧🇳",
            "Bolivia": "🇧🇴",
            "Caribbean Netherlands": "🇧🇶",
            "Brazil": "🇧🇷",
            "Bahamas": "🇧🇸",
            "Bhutan": "🇧🇹",
            "Bouvet Island": "🇧🇻",
            "Botswana": "🇧🇼",
            "Belarus": "🇧🇾",
            "Belize": "🇧🇿",
            "Canada": "🇨🇦",
            "Cocos (Keeling) Islands": "🇨🇨",
            "Congo - Kinshasa": "🇨🇩",
            "Central African Republic": "🇨🇫",
            "Congo - Brazzaville": "🇨🇬",
            "Switzerland": "🇨🇭",
            "Côte d'Ivoire": "🇨🇮",
            "Cook Islands": "🇨🇰",
            "Chile": "🇨🇱",
            "Cameroon": "🇨🇲",
            "China": "🇨🇳",
            "Colombia": "🇨🇴",
            "Clipperton Island": "🇨🇵",
            "Costa Rica": "🇨🇷",
            "Cuba": "🇨🇺",
            "Cape Verde": "🇨🇻",
            "Curaçao": "🇨🇼",
            "Christmas Island": "🇨🇽",
            "Cyprus": "🇨🇾",
            "Czech Republic": "🇨🇿",
            "Germany": "🇩🇪",
            "Diego Garcia": "🇩🇬",
            "Djibouti": "🇩🇯",
            "Denmark": "🇩🇰",
            "Dominica": "🇩🇲",
            "Dominican Republic": "🇩🇴",
            "Algeria": "🇩🇿",
            "Ceuta &amp; Melilla": "🇪🇦",
            "Ecuador": "🇪🇨",
            "Estonia": "🇪🇪",
            "Egypt": "🇪🇬",
            "Western Sahara": "🇪🇭",
            "Eritrea": "🇪🇷",
            "Spain": "🇪🇸",
            "Ethiopia": "🇪🇹",
            "European Union": "🇪🇺",
            "Finland": "🇫🇮",
            "Fiji": "🇫🇯",
            "Falkland Islands": "🇫🇰",
            "Micronesia": "🇫🇲",
            "Faroe Islands": "🇫🇴",
            "France": "🇫🇷",
            "Gabon": "🇬🇦",
            "United Kingdom": "🇬🇧",
            "Grenada": "🇬🇩",
            "Georgia": "🇬🇪",
            "French Guiana": "🇬🇫",
            "Guernsey": "🇬🇬",
            "Ghana": "🇬🇭",
            "Gibraltar": "🇬🇮",
            "Greenland": "🇬🇱",
            "Gambia": "🇬🇲",
            "Guinea": "🇬🇳",
            "Guadeloupe": "🇬🇵",
            "Equatorial Guinea": "🇬🇶",
            "Greece": "🇬🇷",
            "South Georgia &amp; South Sandwich Islands": "🇬🇸",
            "Guatemala": "🇬🇹",
            "Guam": "🇬🇺",
            "Guinea-Bissau": "🇬🇼",
            "Guyana": "🇬🇾",
            "Hong Kong SAR China": "🇭🇰",
            "Heard &amp; McDonald Islands": "🇭🇲",
            "Honduras": "🇭🇳",
            "Croatia": "🇭🇷",
            "Haiti": "🇭🇹",
            "Hungary": "🇭🇺",
            "Canary Islands": "🇮🇨",
            "Indonesia": "🇮🇩",
            "Ireland": "🇮🇪",
            "Israel": "🇮🇱",
            "Isle of Man": "🇮🇲",
            "India": "🇮🇳",
            "British Indian Ocean Territory": "🇮🇴",
            "Iraq": "🇮🇶",
            "Iran": "🇮🇷",
            "Iceland": "🇮🇸",
            "Italy": "🇮🇹",
            "Jersey": "🇯🇪",
            "Jamaica": "🇯🇲",
            "Jordan": "🇯🇴",
            "Japan": "🇯🇵",
            "Kenya": "🇰🇪",
            "Kyrgyzstan": "🇰🇬",
            "Cambodia": "🇰🇭",
            "Kiribati": "🇰🇮",
            "Comoros": "🇰🇲",
            "St. Kitts &amp; Nevis": "🇰🇳",
            "North Korea": "🇰🇵",
            "South Korea": "🇰🇷",
            "Kuwait": "🇰🇼",
            "Cayman Islands": "🇰🇾",
            "Kazakhstan": "🇰🇿",
            "Laos": "🇱🇦",
            "Lebanon": "🇱🇧",
            "St. Lucia": "🇱🇨",
            "Liechtenstein": "🇱🇮",
            "Sri Lanka": "🇱🇰",
            "Liberia": "🇱🇷",
            "Lesotho": "🇱🇸",
            "Lithuania": "🇱🇹",
            "Luxembourg": "🇱🇺",
            "Latvia": "🇱🇻",
            "Libya": "🇱🇾",
            "Morocco": "🇲🇦",
            "Monaco": "🇲🇨",
            "Moldova": "🇲🇩",
            "Montenegro": "🇲🇪",
            "St. Martin": "🇲🇫",
            "Madagascar": "🇲🇬",
            "Marshall Islands": "🇲🇭",
            "Macedonia": "🇲🇰",
            "Mali": "🇲🇱",
            "Myanmar (Burma)": "🇲🇲",
            "Mongolia": "🇲🇳",
            "Macau SAR China": "🇲🇴",
            "Northern Mariana Islands": "🇲🇵",
            "Martinique": "🇲🇶",
            "Mauritania": "🇲🇷",
            "Montserrat": "🇲🇸",
            "Malta": "🇲🇹",
            "Mauritius": "🇲🇺",
            "Maldives": "🇲🇻",
            "Malawi": "🇲🇼",
            "Mexico": "🇲🇽",
            "Malaysia": "🇲🇾",
            "Mozambique": "🇲🇿",
            "Namibia": "🇳🇦",
            "New Caledonia": "🇳🇨",
            "Niger": "🇳🇪",
            "Norfolk Island": "🇳🇫",
            "Nigeria": "🇳🇬",
            "Nicaragua": "🇳🇮",
            "Netherlands": "🇳🇱",
            "Norway": "🇳🇴",
            "Nepal": "🇳🇵",
            "Nauru": "🇳🇷",
            "Niue": "🇳🇺",
            "New Zealand": "🇳🇿",
            "Oman": "🇴🇲",
            "Panama": "🇵🇦",
            "Peru": "🇵🇪",
            "French Polynesia": "🇵🇫",
            "Papua New Guinea": "🇵🇬",
            "Philippines": "🇵🇭",
            "Pakistan": "🇵🇰",
            "Poland": "🇵🇱",
            "St. Pierre &amp; Miquelon": "🇵🇲",
            "Pitcairn Islands": "🇵🇳",
            "Puerto Rico": "🇵🇷",
            "Palestinian Territories": "🇵🇸",
            "Portugal": "🇵🇹",
            "Palau": "🇵🇼",
            "Paraguay": "🇵🇾",
            "Qatar": "🇶🇦",
            "Réunion": "🇷🇪",
            "Romania": "🇷🇴",
            "Serbia": "🇷🇸",
            "Russia": "🇷🇺",
            "Rwanda": "🇷🇼",
            "Saudi Arabia": "🇸🇦",
            "Solomon Islands": "🇸🇧",
            "Seychelles": "🇸🇨",
            "Sudan": "🇸🇩",
            "Sweden": "🇸🇪",
            "Singapore": "🇸🇬",
            "St. Helena": "🇸🇭",
            "Slovenia": "🇸🇮",
            "Svalbard &amp; Jan Mayen": "🇸🇯",
            "Slovakia": "🇸🇰",
            "Sierra Leone": "🇸🇱",
            "San Marino": "🇸🇲",
            "Senegal": "🇸🇳",
            "Somalia": "🇸🇴",
            "Suriname": "🇸🇷",
            "South Sudan": "🇸🇸",
            "São Tomé &amp; Príncipe": "🇸🇹",
            "El Salvador": "🇸🇻",
            "Sint Maarten": "🇸🇽",
            "Syria": "🇸🇾",
            "Swaziland": "🇸🇿",
            "Tristan da Cunha": "🇹🇦",
            "Turks &amp; Caicos Islands": "🇹🇨",
            "Chad": "🇹🇩",
            "French Southern Territories": "🇹🇫",
            "Togo": "🇹🇬",
            "Thailand": "🇹🇭",
            "Tajikistan": "🇹🇯",
            "Tokelau": "🇹🇰",
            "Timor-Leste": "🇹🇱",
            "Turkmenistan": "🇹🇲",
            "Tunisia": "🇹🇳",
            "Tonga": "🇹🇴",
            "Turkey": "🇹🇷",
            "Trinidad &amp; Tobago": "🇹🇹",
            "Tuvalu": "🇹🇻",
            "Taiwan": "🇹🇼",
            "Tanzania": "🇹🇿",
            "Ukraine": "🇺🇦",
            "Uganda": "🇺🇬",
            "United Nations": "🇺🇳",
            "United States": "🇺🇸",
            "Uruguay": "🇺🇾",
            "Uzbekistan": "🇺🇿",
            "Vatican City": "🇻🇦",
            "St. Vincent &amp; Grenadines": "🇻🇨",
            "Venezuela": "🇻🇪",
            "British Virgin Islands": "🇻🇬",
            "U.S. Virgin Islands": "🇻🇮",
            "Vietnam": "🇻🇳",
            "Vanuatu": "🇻🇺",
            "Wallis &amp; Futuna": "🇼🇫",
            "Samoa": "🇼🇸",
            "Kosovo": "🇽🇰",
            "Yemen": "🇾🇪",
            "Mayotte": "🇾🇹",
            "South Africa": "🇿🇦",
            "Zambia": "🇿🇲",
            "Zimbabwe": "🇿🇼",
        },
    },
};
