let language = 'en';

if (localStorage.getItem("language")) {
    language = localStorage.getItem("language");
} else {
    localStorage.setItem("language", "en");
}

function lang() {
    return  eval(language);
}

function currentlang() {
    return localStorage.getItem("language");
}

const en = {
    "language": "English, US",
    "page_home": "Home",
    "page_start": "Start",
    "page_explore": "Explore",
    "page_inbox": "Inbox",
    "page_settings": "Settings",
    "meo_username": "Username",
    "meo_password": "Password",
    "meo_messagebox": "What's on your mind?",
    "meo_goanywhere": "Where would you like to go?",
    "meo_welcome": "Welcome!",
    "meo_bridged": {
        "start": "Bridged",
        "title": "This post has been bridged from another platform."
    },
    "title_chats": "Chats",
    "title_live": "LiveChat",
    "settings_general": "General",
    "settings_appearance": "Appearance",
    "settings_plugins": "Plugins",
    "settings_languages": "Languages",
    "general_sub": {
        "chat": "Chat",
        "accessibility": "Accessibility",
        "misc": "Miscellaneous",
        "acc": "Account",
        "blockedusers": "Blocks",
        "blockedwords": "Blacklisted Words",
        "about": "About",
        "credits": "Credits",
    },
    "general_list": {
        "title": {
            "homepage": "Auto-navigate to Home",
            "consolewarnings": "Disable console warning",
            "blockedmessages": "Hide blocked user messages",
            "invtyping": "Invisible typing",
            "imagewhitelist": "Allow images from any source",
            "censorwords": "Censor blacklisted words",
            "embeds": "Special embeds",
            "reducemotion": "Reduce motion",
            "showpostbuttons": "Always show post buttons",
            "underlinelinks": "Always underline links",
            "entersend": "Don't send on Enter",
            "hideimages": "Hide images",
        },
        "desc": {
            "homepage": "Instead of showing you the Start Page you get directly taken to home",
            "consolewarnings": "Hides warning message from console",
            "blockedmessages": "Show a warning or hide messages completely",
            "invtyping": "Other users won't see you typing",
            "imagewhitelist": "This allows any site to see your IP, use responsibly",
            "censorwords": "Censors words instead of treating them like a blocked message",
            "embeds": "Embeds Tenor GIFS, Youtube Videos, ect. (Uses 3rd party cookies)",
            "reducemotion": "Reduce the intensity of animations and other moving effects",
            "showpostbuttons": "Post buttons always remain visible",
            "underlinelinks": "Make links to websites and other pages stand out more by underlining them",
            "entersend": "Enter key creates newlines instead of sending the post",
            "hideimages": "Blurs images before opening them",
        }
    },
    "appearance_sub": {
        "theme": "Theme",
        "spthemes": "Special Themes",
        "acthemes": "Accessible Themes",
        "ogthemes": "Original Themes",
        "glthemes": "Glass Themes",
        "cstheme": "Custom Theme",
        "cscss": "Custom CSS",
    },
    "plugins_sub": {
        "manage": "Manage",
        "desc": "The plugins repo can be found ",
        "link": "here!"
    },
    "languages_sub": {
        "title": "Select a Language",
        "desc": "Don't see your language here? Help translate on",
        "link": "Github!"
    },
    "inbox_sub": {
        "desc": "Notifications are displayed here.",
    },
    "explore_sub": {
        "trendingunavailable": "Sorry, Trending (Beta) is only available in English for now.",
    },
    "live_sub": {
        "desc": "Messages won't be saved here."
    },
    "login_sub": {
        "title": "Login",
        "desc": "meo by eri, leo by josh",
        "oldpass": "Old Password",
        "newpass": "New Password",
        "agreement": "Terms of Use & Privacy Policy",
    },
    "leave_sub": {
        "desc": "Are you sure you want to leave",
        "end": "?",
    },
    "action": {
        "logout": "Log Out",
        "login": "Log In",
        "signup": "Register",
        "search": "Search",
        "mod": "Moderate",
        "creategc": "Create Chat",
        "leavegc": "Leave Chat?",
        "dmme": "DM Me :)",
        "invite": "Invite People",
        "gohome": "Go Home",
        "cleartokens": "Clear Tokens",
        "changepw": "Change Password",
        "clearls": "Clear Localstorage",
        "deleteacc": "Delete Account",
        "block": "Block",
        "blockuser": "Block User",
        "blockword": "Blacklist Word",
        "run": "Run",
        "close": "Close",
        "back": "Back",
        "opennewtab": "Open in Browser",
        "reply": "Reply",
        "mention": "Mention",
        "report": "Report",
        "delete": "Delete",
        "edit": "Edit",
        "share": "Share",
        "comment": "Comment",
        "nick": "Nickname",
        "create": "Create",
        "reason": "Reason",
        "sendreport": "Send Report",
        "yes": "Yes",
        "confirm": "Confirm",
        "update": "Update",
        "go": "Go",
        "apply": "Apply",
        "savetheme": "Save Theme",
        "loadtheme": "Load Theme",
        "resetplugins": "Disable All",
        "favorite": "Favorite",
    },
    "info": {
        "accexists": "Username Already Taken!",
        "invaliduser": "Invalid Username!",
        "invalidpass": "Invalid Password!",
        "accbanned": "Account Banned!",
        "accdeleted": "Account Deleted!",
        "conflict": "You probably logged in on another client. Refresh the page and log back in to continue.",
        "unknown": "Unknown Login Status:",
        "chatremoved": "You have been removed from the chat you were in.",
        "passupdate": "Your password has been updated!",
        "editingpost": "Editing Post:",
        "reportsent": "Report Sent!",
        "blockedip": "Blocked IP",
        "searchany": "Search for anything!",
        "cleartokens": "This will log you out everywhere.",
        "clearls": "This will log you out.",
        "signup": "By signing up you agree to the Meower TOS",
        "tokenscleared": "Tokens deleted, you will need to log back in",
        "accscheduled": "Account scheduled for deletion",
        "deletewarn": "It will be deleted FOREVER (a very long time!)",
        "changepwwarn": "It will be updated immediately.",
        "tryagain": "Try again",
        "cleared": "Cleared!",
        "plugin": "Restart now to apply new plugins and their settings",
    },
    "reports": {
        "spam": "Spam",
        "harrassment": "Harassment or abuse towards others",
        "language": "Rude, vulgar or offensive language",
        "nsfw": "NSFW (sexual, alcohol, violence, gore, etc.)",
        "scam": "Scams, hacks, phishing or other malicious content",
        "harm": "Threatening violence or real world harm",
        "illegal": "Illegal activity",
        "suicide": "Self-harm/suicide",
        "age": "This person is too young to use Meower",
        "other": "Other",
    },
    "modals": {
        "report": "Report Post",
        "blockword": "Blacklist a Word",
        "blockauser": "Block a User (case sensitive)",
        "blockuser": "Block",
        "unblockuser": "Unblock",
        "bgimage": "Background Image Link",
        "blockedip": "IP Blocked",
        "cleartokens": "Clear Tokens?",
        "changepass": "Change Password",
        "clearls": "Clear Localstorage?",
        "deleteacc": "Delete Account?",
        "share": "Share",
        "plugin": "Refresh Required!",
        "uploadimage": "Upload an image",
    },
    "profile": {
        "quote": "Quote",
        "persona": "Personalization",
        "profilecolor": "Profile Color",
        "profilepic": "Profile Picture",
    },
    "chats": { // update
        "members": "Members"
    }
}

const enuk = {
    "language": "English, UK",
    "page_home": "Home",
    "page_start": "Start",
    "page_explore": "Explore",
    "page_inbox": "Inbox",
    "page_settings": "Settings",
    "meo_username": "Username",
    "meo_password": "Password",
    "meo_messagebox": "What's on your mind?",
    "meo_goanywhere": "Where would you like to go?",
    "meo_welcome": "Welcome!",
    "meo_bridged": {
        "start": "Bridged",
        "title": "This post has been bridged from another platform.",
    },
    "title_chats": "Chats",
    "title_live": "LiveChat",
    "settings_general": "General",
    "settings_appearance": "Appearance",
    "settings_plugins": "Plugins",
    "settings_languages": "Languages",
    "general_sub": {
        "chat": "Chat",
        "accessibility": "Accessibility",
        "misc": "Miscellaneous",
        "acc": "Account",
        "blockedusers": "Blocks",
        "blockedwords": "Blacklisted Words",
        "about": "About",
        "credits": "Credits",
    },
    "general_list": {
        "title": {
            "homepage": "Auto-navigate to Home",
            "consolewarnings": "Disable console warning",
            "blockedmessages": "Hide blocked user messages",
            "invtyping": "Invisible typing",
            "imagewhitelist": "Allow images from any source",
            "censorwords": "Censor blacklisted words",
            "embeds": "Special embeds",
            "reducemotion": "Reduce motion",
            "showpostbuttons": "Always show post buttons",
            "underlinelinks": "Always underline links",
            "entersend": "Don't send on Enter",
            "hideimages": "Hide images",
        },
        "desc": {
            "homepage": "Instead of showing you the Start Page, you're taken directly to the Home.",
            "consolewarnings": "Hides warning messages from the console.",
            "blockedmessages": "Shows a warning or hides messages completely.",
            "invtyping": "Other users won't see you typing.",
            "imagewhitelist": "Allows images from any site, use responsibly.",
            "censorwords": "Censors words instead of treating them like a blocked message.",
            "embeds": "Embeds Tenor GIFs, YouTube Videos, etc. (Uses 3rd party cookies).",
            "reducemotion": "Reduces the intensity of animations and other moving effects.",
            "showpostbuttons": "Post buttons always remain visible.",
            "underlinelinks": "Makes links to websites and other pages stand out more by underlining them.",
            "entersend": "Enter key creates newlines instead of sending the post",
            "hideimages": "Blurs images before opening them",
        },
    },
    "appearance_sub": {
        "theme": "Theme",
        "spthemes": "Special Themes",
        "acthemes": "Accessible Themes",
        "ogthemes": "Original Themes",
        "glthemes": "Glass Themes",
        "cstheme": "Custom Theme",
        "cscss": "Custom CSS",
    },
    "plugins_sub": {
        "manage": "Manage",
        "desc": "The plugins repo can be found ",
        "link": "here!"
    },
    "languages_sub": {
        "title": "Select a Language",
        "desc": "Don't see your language here? Help translate on",
        "link": "Github!"
    },
    "inbox_sub": {
        "desc": "Notifications are displayed here.",
    },
    "explore_sub": {
        "trendingunavailable": "Sorry, Trending (Beta) is only available in English for now.",
    },
    "live_sub": {
        "desc": "Messages won't be saved here."
    },
    "login_sub": {
        "title": "Login",
        "desc": "meo by eri, leo by josh",
        "oldpass": "Old Password",
        "newpass": "New Password",
        "agreement": "Terms of Use & Privacy Policy",
    },
    "leave_sub": {
        "desc": "Are you sure you want to leave",
        "end": "?",
    },
    "action": {
        "logout": "Log Out",
        "login": "Log In",
        "signup": "Register",
        "search": "Search",
        "mod": "Moderate",
        "creategc": "Create Chat",
        "leavegc": "Leave Chat?",
        "dmme": "DM Me :)",
        "invite": "Invite People",
        "gohome": "Go Home",
        "cleartokens": "Clear Tokens",
        "changepw": "Change Password",
        "clearls": "Clear Local Storage",
        "deleteacc": "Delete Account",
        "block": "Block",
        "blockuser": "Block User",
        "blockword": "Blacklist Word",
        "run": "Run",
        "close": "Close",
        "back": "Back",
        "opennewtab": "Open in Browser",
        "reply": "Reply",
        "mention": "Mention",
        "report": "Report",
        "delete": "Delete",
        "edit": "Edit",
        "share": "Share",
        "comment": "Comment",
        "nick": "Nickname",
        "create": "Create",
        "reason": "Reason",
        "sendreport": "Send Report",
        "yes": "Yes",
        "confirm": "Confirm",
        "update": "Update",
        "go": "Go",
        "apply": "Apply",
        "savetheme": "Save Theme",
        "loadtheme": "Load Theme",
        "resetplugins": "Disable All",
        "favorite": "Favourite",
    },
    "info": {
        "accexists": "Username Already Taken!",
        "invaliduser": "Invalid Username!",
        "invalidpass": "Invalid Password!",
        "accbanned": "Account Banned!",
        "accdeleted": "Account Deleted!",
        "conflict": "You probably logged in on another client. Refresh the page and log back in to continue.",
        "unknown": "Unknown Login Status:",
        "chatremoved": "You have been removed from the chat you were in.",
        "passupdate": "Your password has been updated!",
        "editingpost": "Editing Post:",
        "reportsent": "Report Sent!",
        "blockedip": "Blocked IP",
        "searchany": "Search for anything!",
        "cleartokens": "This will log you out everywhere.",
        "clearls": "This will log you out.",
        "signup": "By signing up you agree to the Meower TOS",
        "tokenscleared": "Tokens deleted, you will need to log back in",
        "accscheduled": "Account scheduled for deletion",
        "deletewarn": "It will be deleted FOREVER (a very long time!)",
        "changepwwarn": "It will be updated immediately.",
        "tryagain": "Try again",
        "cleared": "Cleared!",
        "plugin": "Restart now to apply new plugins and their settings",
    },
    "reports": {
        "spam": "Spam",
        "harassment": "Harassment or abuse towards others",
        "language": "Rude, vulgar or offensive language",
        "nsfw": "NSFW (sexual, alcohol, violence, gore, etc.)",
        "scam": "Scams, hacks, phishing or other malicious content",
        "harm": "Threatening violence or real world harm",
        "illegal": "Illegal activity",
        "suicide": "Self-harm/suicide",
        "age": "This person is too young to use Meower",
        "other": "Other",
    },
    "modals": {
        "report": "Report Post",
        "blockword": "Blacklist a Word",
        "blockauser": "Block a User (case sensitive)",
        "blockuser": "Block",
        "unblockuser": "Unblock",
        "bgimage": "Background Image Link",
        "blockedip": "IP Blocked",
        "cleartokens": "Clear Tokens?",
        "changepass": "Change Password",
        "clearls": "Clear Local Storage?",
        "deleteacc": "Delete Account?",
        "share": "Share",
        "plugin": "Refresh Required!",
        "uploadimage": "Upload an image",
    },
    "profile": {
        "quote": "Quote",
        "persona": "Personalisation",
        "profilecolor": "Profile Colour",
        "profilepic": "Profile Picture",
    },
    "chats": { // update
        "members": "Members"
    }
}

const es = {
    //Spanish Translation by ethernet/Ethernet0
    //Last updated 6/8/2024 - version I
    //hi eri! :)
    "language": "Español (América Latina)",
    "page_home": "Home",
    "page_start": "Inicio",
    "page_explore": "Explorar",
    "page_inbox": "Buzón",
    "page_settings": "Configuracion",
    "meo_username": "Nombre de Usuario",
    "meo_password": "Contraseña",
    "meo_messagebox": "¿En qué estás pensando?",
    "meo_goanywhere": "A dónde le gustaría ir?",
    "meo_welcome": "¡Bienvenido!",
    "meo_bridged": {
        "start": "Puenteado",
        "title": "Este mensaje ha sido puenteado desde otra plataforma."
    },
    "title_chats": "Chats",
    "title_live": "LiveChat", // update
    "settings_general": "General",
    "settings_appearance": "Apariencia",
    "settings_plugins": "Plugins (expansiones)",
    "settings_languages": "Idiomas",
    "general_sub": {
        "chat": "Chat",
        "accessibility": "Accesibilidad",
        "misc": "Otros",
        "acc": "Cuenta",
        "blockedusers": "Usuarios Bloqueados",
        "blockedwords": "Palabras Bloqueadas",
        "about": "Acerca De",
        "credits": "Creditos",
    },
    "general_list": {
        "title": {
            "homepage": "Auto-navegar a Home",
            "consolewarnings": "Desactivar advertencias de la consola",
            "blockedmessages": "Hide blocked user messages",
            "invtyping": "Escritura/Tecleado invisible",
            "imagewhitelist": "Permitir imágenes de cualquier fuente",
            "censorwords": "Censurar palabras de la lista negra",
            "embeds": "Incorporaciones especiales",
            "reducemotion": "Reducir movimiento",
            "showpostbuttons": "Siempre mostrar botones en mensajes",
            "underlinelinks": "Siempre subrayar enlaces",
            "entersend": "Don't send on Enter", // update
            "hideimages": "Hide images", // update
        },
        "desc": {
            "homepage": "En lugar de mostrarte la página de inicio, navegar directamente a home",
            "consolewarnings": "Oculta los mensajes de alerta de la consola",
            "blockedmessages": "Mostrar una advertencia (o) ocultar completamente los mensajes bloqueados",
            "invtyping": "Otros usuarios no te verán teclear",
            "imagewhitelist": "Esto permite que cualquier sitio vea tu direction IP, use responsibly",
            "censorwords": "Censurar palabras en lugar de tratarlas como un mensaje bloqueado",
            "embeds": "Incoroporar GIFs de Tenor, Videos de Youtube, ect. (Usa cookies de 3ª part)",
            "reducemotion": "Reducir la intensidad de las animaciones y otros efectos con movimiento",
            "showpostbuttons": "Los botones en las publicaciónes/mensajes permanecen siempre visibles",
            "underlinelinks": "Subrayar los enlaces a sitios web y otras páginas para que destaquen más.",
            "entersend": "Enter key creates newlines instead of sending the post", // update
            "hideimages": "Blurs images before opening them", // update
        }
    },
    "appearance_sub": {
        "theme": "Tema",
        "spthemes": "Temas Speciales",
        "acthemes": "Temas Accesibles",
        "ogthemes": "Temas Originales",
        "glthemes": "Temas de Vidrio",
        "cstheme": "Tema Personalizado",
        "cscss": "Código CSS personalizado",
    },
    "plugins_sub": {
        "manage": "Manage",
        "desc": "The plugins repo can be found ",
        "link": "here!"
    },
    "languages_sub": {
        "title": "Select a Language",
        "desc": "Don't see your language here? Help translate on",
        "link": "Github!"
    },
    "inbox_sub": {
        "desc": "Las notificaciones aparecen aquí.",
    },
    "explore_sub": {
        "trendingunavailable": "Lo sentimos, Trending (Beta) solo está disponible en inglés por ahora.",
    },
    "live_sub": {
        "desc": "Messages won't be saved here." // update
    },
    "login_sub": {
        "title": "Iniciar sesión",
        "desc": "meo por eri, leo por josh - Traducido al español por ether",
        "oldpass": "Contraseña Anterior",
        "newpass": "Contraseña Nueva",
        "agreement": "Términos de servicio y Política de privacidad"
    },
    "leave_sub": { // update
        "desc": "Are you sure you want to leave",
        "end": "?",
    },
    "action": {
        "logout": "Cerrar Sesión",
        "login": "Iniciar Sesión",
        "signup": "Registrarse",
        "search": "Búsqueda",
        "mod": "Moderar",
        "creategc": "Crear Chat (Grupo)",
        "leavegc": "Leave Chat?", // update
        "dmme": "DM Me :)",
        "invite": "Invitar Personas",
        "gohome": "Ir a Home",
        "cleartokens": "Borrar Fichas de sesión (Tokens)",
        "changepw": "Cambiar Contraseña",
        "clearls": "Borrar Almacenamiento Local",
        "deleteacc": "Eliminar Cuenta",
        "block": "Bloquear",
        "blockuser": "Bloquear Usuario",
        "blockword": "Añadir Palabra a la Lista Negra",
        "run": "Run (Ejecutar)",
        "close": "Cerrar",
        "back": "Atrás",
        "opennewtab": "Abrir En Navegador Web",
        "reply": "Responder",
        "mention": "Mencionar Usuario",
        "report": "Denunciar",
        "delete": "Eliminar",
        "edit": "Editar",
        "share": "Compartir",
        "comment": "Comentar",
        "nick": "Sobrenombre",
        "create": "Crear",
        "reason": "Razón",
        "sendreport": "Enviar Denuncia",
        "yes": "Si",
        "confirm": "Confirmar",
        "update": "Actualizar",
        "go": "Ir",
        "apply": "Aplicar",
        "savetheme": "Save Theme (Salvar Tema)",
        "loadtheme": "Load Theme (Cargar Tema)",
        "resetplugins": "Disable All", // update
        "favorite": "Favorite", // update
    },
    "info": {
        "accexists": "¡Nombre de Usuario ya Ocupado!",
        "invaliduser": "¡Nombre de Usuario Inválido!",
        "invalidpass": "¡Contraseña Inválida!",
        "accbanned": "¡Cuenta Vetada!",
        "accdeleted": "¡Cuenta eliminada!",
        "conflict": "Es probable que hayas iniciado una sesión en otro servicio/ciber cliente. Refresque la página y vuelva a iniciar una sesión para continuar.",
        "unknown": "Estado de inicio de sesión desconocido:",
        "chatremoved": "Has sido eliminado del chat/grupo en el que estabas.",
        "passupdate": "Su contraseña ha sido actualizada. Es posible que tenga que volver a iniciar su sesión.",
        "editingpost": "Editando Mensaje:",
        "reportsent": "¡Denuncia enviada!",
        "blockedip": "Dirección IP bloqueada",
        "searchany": "¡Busca cualquier cosa!",
        "cleartokens": "Esto cerrará tu sesión en todas partes",
        "clearls": "Esto cerrará tu sesión.",
        "signup": "Al registrarte aceptas los términos y condiciones de servicio de Meower",
        "tokenscleared": "Fichas de sesión (Session Tokens) eliminadas, tendrá que volver a iniciar sesión",
        "accscheduled": "Cuenta de usuario programada para su eliminación",
        "deletewarn": "Se borrará PARA SIEMPRE (¡Un tiempo muy largo!)",
        "changepwwarn": "It will be updated immediately.", //update
        "tryagain": "Inténtalo de nuevo",
        "cleared": "¡Borrado!",
        "plugin": "Restart now to apply new plugins and their settings", // update
    },
    "reports": {
        "spam": "Spam (Basura)",
        "harassment": "Acoso o abuso hacia otras personas",
        "language": "Lenguaje grosero, vulgar (y/o) ofensivo",
        "nsfw": "NSFW (sexual, alcohol, violencia, sangriento, etc.)",
        "scam": "Estafas, hackeos, phishing (y/o) otros contenidos maliciosos",
        "harm": "Amenazas de violencia o daños en el mundo real",
        "illegal": "Actividad ilegal",
        "suicide": "Autolesión/suicidio",
        "age": "Esta persona es demasiado/a joven para usar Meower",
        "other": "Otro",
    },
    "modals": {
        "report": "Denunciar Mensaje",
        "blockword": "Añadir Palabra a la Lista Negra",
        "blockauser": "Block a User (case sensitive)",
        "blockuser": "Bloquear",
        "unblockuser": "Desbloquear",
        "bgimage": "Enlace de Imagen de Fondo (Background Image Link)",
        "blockedip": "Dirección IP bloqueada",
        "cleartokens": "Borrar Fichas de sesión (Tokens)?",
        "changepass": "Cambiar Contraseña",
        "clearls": "Borrar Almacenamiento Local?",
        "uploadimage": "Subir una imagen",
    },
    "profile": {
        "quote": "Cita de perfil",
        "persona": "Personalización",
        "profilecolor": "Color del perfil",
        "profilepic": "Foto de perfil",
    },
    "chats": { // update
        "members": "Members"
    }
}

const de = {
    // credit: mybearworld
    "language": "Deutsch, Deutschland",
    "page_home": "Home",
    "page_start": "Start",
    "page_explore": "Entdecken",
    "page_inbox": "Posteingang",
    "page_settings": "Einstellungen",
    "meo_username": "Benutzername",
    "meo_password": "Passwort",
    "meo_messagebox": "Worüber denkst du nach?",
    "meo_goanywhere": "Wo würdest du gerne hingehen?",
    "meo_welcome": "Willkommen!",
    "meo_bridged": {
        "start": "Extern", // translated as "external" because "überbrückt" would sound really awkward
        "title": "Dieser Post wurde auf einer externen Platform geschickt."
    },
    "title_chats": "Chats",
    "title_live": "LiveChat", // update
    "settings_general": "Allgemein",
    "settings_appearance": "Aussehen",
    "settings_plugins": "Plugins",
    "settings_languages": "Sprachen",
    "general_sub": {
        "chat": "Chat",
        "accessibility": "Barrierenfreiheit",
        "misc": "Sonstiges",
        "acc": "Konto",
        "blockedusers": "Blockiert",
        "blockedwords": "Verbotene Wörter",
        "about": "Über",
        "credits": "Dankaussagungen",
    },
    "general_list": {
        "title": {
            "homepage": "Automatisch zu Home gehen",
            "consolewarnings": "Konsolenwarnung ausschalten",
            "blockedmessages": "Nachrichten von blockierten Nutzern verstecken",
            "invtyping": "Durchsichtiges Tippen",
            "imagewhitelist": "Bilder von jeder Quelle erlauben",
            "censorwords": "Verbotene Wörter blockieren",
            "embeds": "Besondere Einbettungen",
            "reducemotion": "Bewegung reduzieren",
            "showpostbuttons": "Postknöpfe immer zeigen",
            "underlinelinks": "Links immer unterstreichen",
            "entersend": "Don't send on Enter", // update
            "hideimages": "Hide images", // update
        },
        "desc": {
            "homepage": "Direkt zu Home navigieren, statt die Startseite anzuzeigen",
            "consolewarnings": "Die Warnmeldung in der Konsole nicht zeigen",
            "blockedmessages": "Nur eine Warnung zeigen, oder die Nachricht komplett verstecken",
            "invtyping": "Andere Nutzer werden dich nicht tippen sehen",
            "imagewhitelist": "Dadurch kann dadurch deine IP-Adresse sehen, nutze das verantwortlich",
            "censorwords": "Zensiert Wörter, statt sie als blockierte Nachricht zu sehen",
            "embeds": "Tenor-GIFS, YouTube-Videos etc. einbetten (Cookies dritter Parteien)",
            "reducemotion": "Die Intensität der Animationen und andere Bewegungseffekte reduzieren",
            "showpostbuttons": "Postknöpfe bleiben immer sichtbar",
            "underlinelinks": "Links zu Websiten und anderen Seiten unterstreichen und damit hervorheben",
            "entersend": "Enter key creates newlines instead of sending the post", // update
            "hideimages": "Blurs images before opening them", // update
        }
    },
    "appearance_sub": {
        "theme": "Aussehen",
        "spthemes": "Besondere Aussehen",
        "acthemes": "Barrierenfreie Aussehen",
        "ogthemes": "Ursprüngliche Aussehen",
        "glthemes": "Glasaussehen",
        "cstheme": "Eigenes Aussehen",
        "cscss": "Eigenes CSS",
    },
    "plugins_sub": {
        "manage": "Einstellen",
        "desc": "The plugins repo can be found ",
        "link": "here!"
    },
    "languages_sub": {
        "title": "Wähle eine Sprache",
        "desc": "Siehst du deine Sprache hier nicht? Übersetze sie auf",
        "link": "Github!"
    },
    "inbox_sub": {
        "desc": "Benachrichtigungen werden hier angezeigt.",
    },
    "explore_sub": {
        "trendingunavailable": "Entschuldigung, Trending (Beta) ist derzeit nur auf Englisch verfügbar.",
    },
    "live_sub": {
        "desc": "Messages won't be saved here." // update
    },
    "login_sub": {
        "title": "Anmelden",
        "desc": "meo von eri, leo von josh",
        "oldpass": "Altes Passwort",
        "newpass": "Neues Passwort",
        "agreement": "Geschäftsbedingungen und Datenschutzerklärung"
    },
    "leave_sub": { // update
        "desc": "Are you sure you want to leave",
        "end": "?",
    },
    "action": {
        "logout": "Abmelden",
        "login": "Anmelden",
        "signup": "Konto erstellen",
        "search": "Suchen",
        "mod": "Moderieren",
        "creategc": "Chat erstellen",
        "leavegc": "Leave Chat?", // update
        "dmme": "Schicke mir eine Nachricht :)",
        "invite": "Menschen einladen",
        "gohome": "Zu Home gehen",
        "cleartokens": "Tokens löschen",
        "changepw": "Passwort ändern",
        "clearls": "Lokalen Speicherplatz löschen",
        "deleteacc": "Konto löschen",
        "block": "Blockieren",
        "blockuser": "Nutzer blockieren",
        "blockword": "Wort verbieten",
        "run": "Ausführen",
        "close": "Schließen",
        "back": "Zurück",
        "opennewtab": "Im Browser öffnen",
        "reply": "Antworten",
        "mention": "Ansprechen",
        "report": "Melden",
        "delete": "Löschen",
        "edit": "Bearbeiten",
        "share": "Teilen",
        "comment": "Kommentieren",
        "nick": "Spitzname",
        "create": "Erstellen",
        "reason": "Grund",
        "sendreport": "Meldung senden",
        "yes": "Ja",
        "confirm": "Bestätigen",
        "update": "Aktualisieren",
        "go": "Los",
        "apply": "Übernehmen",
        "savetheme": "Aussehen speichern",
        "loadtheme": "Aussehen laden",
        "resetplugins": "Alles ausschalten",
        "favorite": "Favorite", // update
    },
    "info": {
        "accexists": "Der Benutzername wird schon benutzt!",
        "invaliduser": "Ungültiger Benutzername!",
        "invalidpass": "Ungültiges Passwort!",
        "accbanned": "Konto gebannt!",
        "accdeleted": "Konto gelöscht!",
        "conflict": "Du hast dich vermutlich bei einem anderen Client angemeldet. Lade die Seite neu und melde dich wieder ein, um weiterzumachen.",
        "unknown": "Unbekannter Anmeldestatus:",
        "chatremoved": "Du wurdest von dem Chat, in dem du bist, entfernt.",
        "passupdate": "Dein Passwort wurde aktualisiert!",
        "editingpost": "Post wird bearbeitet:",
        "reportsent": "Meldung wurde gesendet!",
        "blockedip": "Blockierte IP",
        "searchany": "Suche nach irgendetwas!",
        "cleartokens": "Das wird dich überall abmelden.",
        "clearls": "Das wird dich anmelden.",
        "signup": "Wenn du ein Konto erstellst, stimmst du den Nutzungsbedingungen von Meower zu",
        "tokenscleared": "Tokens wurden gelöscht, du musst dich erneut anmelden",
        "accscheduled": "Konto wird gelöscht werden",
        "deletewarn": "Es wird FÜR IMMER (eine sehr lange Zeit!) gelöscht",
        "changepwwarn": "It will be updated immediately.", //update
        "tryagain": "Versuche es erneut",
        "cleared": "Gelöscht!",
        "plugin": "Jetzt neu laden um neue Plugins und ihre Einstellungen anzuwenden",
    },
    "reports": {
        "spam": "Spam",
        "harrassment": "Hassrede oder Missbrauch anderer",
        "language": "Unhöfliche, vulgäre oder Rude, vulgar or anstößige Sprache",
        "nsfw": "NSFW (Sexuelles, Alkohol, Gewalt, Blut, usw.)",
        "scam": "Betrug, Hacks, Phishing oder andere bösartigen Inhalte",
        "harm": "Drohung von Gewalt oder Schaden",
        "illegal": "Illegale Aktivität",
        "suicide": "Selbstschaden, Suizid",
        "age": "Diese Person ist zu jung, um Meower zu benutzen",
        "other": "Anderes",
    },
    "modals": {
        "report": "Post melden",
        "blockword": "Ein Wort verbieten",
        "blockauser": "Einen User blockieren (Groß- und Kleinschreibung zählt)",
        "blockuser": "Blockieren",
        "unblockuser": "Blockierung aufheben",
        "bgimage": "Link von Hintergrundbild",
        "blockedip": "IP-Blockiert",
        "cleartokens": "Tokens löschen?",
        "changepass": "Passwort ändern",
        "clearls": "Lokalen Speicherplatz löschen?",
        "deleteacc": "Konto löschen?",
        "share": "Teilen",
        "plugin": "Aktualisierung benötigt!",
        "uploadimage": "Lade ein Bild hoch",
    },
    "profile": {
        "quote": "Zitat",
        "persona": "Personalisierung",
        "profilecolor": "Profilfarbe",
        "profilepic": "Profilbild",
    },
    "chats": { // update
        "members": "Members"
    }
}