let language = 'en';
let loadedLang = {};

function lang() {
    return loadedLang;
}

// thanks ChatGPT :)
// - Tnix
function deepCopy(obj) {
    if (obj === null || typeof obj !== 'object') {
      return obj;
    }
  
    if (Array.isArray(obj)) {
      const arrCopy = [];
      for (let i = 0; i < obj.length; i++) {
        arrCopy[i] = deepCopy(obj[i]);
      }
      return arrCopy;
    }
  
    const objCopy = {};
    for (let key in obj) {
      if (obj.hasOwnProperty(key)) {
        objCopy[key] = deepCopy(obj[key]);
      }
    }
    return objCopy;
}
function deepMerge(target, source) {
    if (typeof target !== 'object' || target === null) {
      return source;
    }
    
    if (typeof source !== 'object' || source === null) {
      return target;
    }
  
    for (let key in source) {
      if (source.hasOwnProperty(key)) {
        if (typeof source[key] === 'object' && source[key] !== null) {
          if (!target[key] || typeof target[key] !== 'object') {
            target[key] = Array.isArray(source[key]) ? [] : {};
          }
          deepMerge(target[key], source[key]);
        } else {
          target[key] = source[key];
        }
      }
    }
  
    return target;
}

function setlang(lang) {
    localStorage.setItem("language", lang);
    language = lang;
    if (lang === "en") {
        loadedLang = en;
    } else {
        loadedLang = deepMerge(deepCopy(en), deepCopy(eval(lang)));
    }
}

const en = {
    "reh": "English, US",
    "language": "English, US",
    "page_home": "Home",
    "page_start": "Start",
    "page_explore": "Explore",
    "page_inbox": "Inbox",
    "page_settings": "Settings",
    "meo_username": "Username",
    "meo_password": "Password",
    "meo_messagebox": Math.random() < 1/25 ? "Whar's on your mind?" : "What's on your mind?",
    "meo_goanywhere": "Where would you like to go?",
    "meo_welcome": "Welcome!",
    "meo_bridged": {
        "start": "Bridged",
        "title": "This post has been bridged from another platform."
    },
    "title_chats": "Chats",
    "title_live": "Livechat",
    "settings_general": "General",
    "settings_appearance": "Appearance",
    "settings_plugins": "Plugins",
    "settings_languages": "Languages",
    "general_sub": {
        "chat": "Chat",
        "accessibility": "Accessibility",
        "misc": "Miscellaneous",
        "acc": "Account",
        "blockedusers": "Blocks",
        "blockedwords": "Blacklisted Words",
        "about": "About",
        "credits": "Credits",
        "contrib": "Contribute",
        "privacy": "Privacy & Safety",
    },
    "general_list": {
        "title": {
            "homepage": "Auto-navigate to Home",
            "consolewarnings": "Disable console warning",
            "blockedmessages": "Hide blocked user messages",
            "invtyping": "Invisible typing",
            "imagewhitelist": "Allow images from any source",
            "censorwords": "Censor blacklisted words",
            "embeds": "Special embeds",
            "reducemotion": "Reduce motion",
            "showpostbuttons": "Always show post buttons",
            "underlinelinks": "Always underline links",
            "magnify": "Magnify text",
            "entersend": "Don't send on Enter",
            "hideimages": "Hide images",
            "notifications": "Allow Notifications",
            "widemode": "New Desktop Experience",
            "discord": "Discord Post Layout",
        },
        "desc": {
            "homepage": "Instead of showing you the Start Page you get directly taken to home",
            "consolewarnings": "Hides warning message from console",
            "blockedmessages": "Show a warning or hide messages completely",
            "invtyping": "Other users won't see you typing",
            "imagewhitelist": "This allows any site to see your IP, use responsibly",
            "censorwords": "Censors words instead of treating them like a blocked message",
            "embeds": "Embeds Tenor GIFS, Youtube Videos, ect. (Uses 3rd party cookies)",
            "reducemotion": "Reduce the intensity of animations and other moving effects",
            "showpostbuttons": "Post buttons always remain visible",
            "underlinelinks": "Make links to websites and other pages stand out more by underlining them",
            "magnify": "Enlargens and bolds text to be easier to read with poor eyesight (Requires refresh)",
            "entersend": "Enter key creates newlines instead of sending the post",
            "hideimages": "Blurs images before opening them",
            "notifications": "This will ask for notification permissions (Experimental)",
            "widemode": "Enables new desktop experience (Experiemental, Requires refresh)",
            "discord": "Reverses the post order to be more like Discord (Experiemental, Requires refresh)",
        }
    },
    "appearance_sub": {
        "theme": "Theme",
        "spthemes": "Special Themes",
        "acthemes": "Accessible Themes",
        "ogthemes": "Original Themes",
        "glthemes": "Glass Themes",
        "cstheme": "Custom Theme",
        "cscss": "Custom CSS",
    },
    "plugins_sub": {
        "manage": "Manage",
        "desc": "The plugins repo can be found ",
        "link": "here!"
    },
    "languages_sub": {
        "title": "Select a Language",
        "desc": "Don't see your language here? Help translate on",
        "link": "Github!",
        "other": "Other Languages"
    },
    "inbox_sub": {
        "desc": "Notifications are displayed here.",
    },
    "live_sub": {
        "desc": "Messages won't be saved here."
    },
    "login_sub": {
        "title": "Login",
        "desc": "This client was made by eri :>",
        "oldpass": "Old Password",
        "newpass": "New Password",
        "agreement": "Terms of Use & Privacy Policy",
    },
    "leave_sub": {
        "desc": "Are you sure you want to leave",
        "end": "?",
    },
    "action": {
        "logout": "Log Out",
        "login": "Log In",
        "signup": "Register",
        "search": "Search",
        "mod": "Moderate",
        "creategc": "Create Chat",
        "leavegc": "Leave Chat?",
        "dmme": "DM Me :)",
        "invite": "Invite People",
        "gohome": "Go Home",
        "cleartokens": "Clear Tokens",
        "changepw": "Change Password",
        "clearls": "Clear Localstorage",
        "deleteacc": "Delete Account",
        "block": "Block",
        "blockuser": "Block User",
        "blockword": "Blacklist Word",
        "run": "Run",
        "close": "Close",
        "back": "Back",
        "opennewtab": "Open in Browser",
        "reply": "Reply",
        "mention": "Mention",
        "report": "Report",
        "delete": "Delete",
        "edit": "Edit",
        "share": "Share",
        "comment": "Comment",
        "nick": "Nickname",
        "create": "Create",
        "reason": "Reason",
        "sendreport": "Send Report",
        "yes": "Yes",
        "confirm": "Confirm",
        "update": "Update",
        "go": "Go",
        "apply": "Apply",
        "savetheme": "Save Theme",
        "loadtheme": "Load Theme",
        "resetplugins": "Disable All",
        "favorite": "Favorite",
        "download": "Download",
        "add": "Add",
        "adduser": "Add Member", // update
        "transfer": "Transfer Ownership", // update
        "bug": "Report Bug", // update
        "datarequest": "Request Data", // update
        "discuss": "Discuss", // update
    },
    "info": {
        "accexists": "Username Already Taken!",
        "invaliduser": "Invalid Username!",
        "invalidpass": "Invalid Password!",
        "invalidcreds": "Invalid username or password!",
        "accbanned": "Account Banned!",
        "accdeleted": "Account Deleted!",
        "conflict": "You probably logged in on another client. Refresh the page and log back in to continue.",
        "unknown": "Unknown Login Status:",
        "chatremoved": "You have been removed from the chat you were in.",
        "passupdate": "Your password has been updated!",
        "editingpost": "Editing Post:",
        "reportsent": "Report Sent!",
        "blockedip": "Blocked IP",
        "searchany": "Search for anything!",
        "cleartokens": "This will log you out everywhere.",
        "clearls": "This will log you out.",
        "signup": "By signing up you agree to the Meower TOS",
        "tokenscleared": "Tokens deleted, you will need to log back in",
        "accscheduled": "Account scheduled for deletion",
        "deletewarn": "It will be deleted FOREVER (a very long time!)",
        "changepwwarn": "It will be updated immediately.",
        "tryagain": "Try again",
        "cleared": "Cleared!",
        "plugin": "Restart now to apply new plugins and their settings",
        "replieslimit": "You can only reply up to 10 posts at a time!", // update
    },
    "reports": {
        "spam": "Spam",
        "harassment": "Harassment or abuse towards others",
        "language": "Rude, vulgar or offensive language",
        "nsfw": "NSFW (sexual, alcohol, violence, gore, etc.)",
        "scam": "Scams, hacks, phishing or other malicious content",
        "harm": "Threatening violence or real world harm",
        "illegal": "Illegal activity",
        "suicide": "Self-harm/suicide",
        "age": "This person is too young to use Meower",
        "other": "Other",
    },
    "modals": {
        "report": "Report Post",
        "blockword": "Blacklist a Word",
        "blockauser": "Block a User (case sensitive)",
        "blockuser": "Block",
        "unblockuser": "Unblock",
        "bgimage": "Background Image Link",
        "blockedip": "IP Blocked",
        "cleartokens": "Clear Tokens?",
        "changepass": "Change Password",
        "clearls": "Clear Localstorage?",
        "deleteacc": "Delete Account?",
        "share": "Share",
        "plugin": "Refresh Required!",
        "shortcuts": "Shortcuts",
        "copyuser": "Copied username to clipboard!",
    },
    "profile": {
        "quote": "Quote",
        "persona": "Personalization",
        "profilecolor": "Profile Color",
        "profilepic": "Profile Picture",
    },
    "chats": { // update
        "owner": "Ownership",
        "members": "Members"
    }
}

const enuk = {
    "language": "English, UK",
    "meo_bridged": {
        "start": "Bridged",
        "title": "This post has been bridged from another platform."
    },
    "general_sub": {
    },
    "general_list": {
        "title": {
        },
        "desc": {
            "homepage": "Instead of showing you the Start Page, you're taken directly to the Home.",
            "consolewarnings": "Hides warning messages from the console.",
            "blockedmessages": "Shows a warning or hides messages completely.",
            "invtyping": "Other users won't see you typing.",
            "imagewhitelist": "Allows images from any site, use responsibly.",
            "censorwords": "Censors words instead of treating them like a blocked message.",
            "embeds": "Embeds Tenor GIFs, YouTube Videos, etc. (Uses 3rd party cookies).",
            "reducemotion": "Reduces the intensity of animations and other moving effects.",
            "showpostbuttons": "Post buttons always remain visible.",
            "underlinelinks": "Makes links to websites and other pages stand out more by underlining them.",
        },
    },
    "appearance_sub": {
    },
    "plugins_sub": {
    },
    "languages_sub": {
    },
    "inbox_sub": {
    },
    "live_sub": {
    },
    "login_sub": {
    },
    "leave_sub": {
    },
    "action": {
        "clearls": "Clear Local Storage",
        "favorite": "Favourite",
    },
    "info": {
    },
    "reports": {
    },
    "modals": {
        "clearls": "Clear Local Storage?",
    },
    "profile": {
        "persona": "Personalisation",
        "profilecolor": "Profile Colour",
    },
    "chats": {
    }
}

const es = {
    //Spanish Americas Translation by ethernet/Ethernet0
    //Last updated 6/4/2024(2024-06-04) - version 1.1
    //hi eri! :)
    "language": "Español Latinoamérica", //corrected - ethernet0 v1.1
    "page_home": "Home",
    "page_start": "Inicio",
    "page_explore": "Explorar",
    "page_inbox": "Buzón",
    "page_settings": "Configuracion",
    "meo_username": "Nombre de Usuario",
    "meo_password": "Contraseña",
    "meo_messagebox": "¿En qué estás pensando?",
    "meo_goanywhere": "A dónde le gustaría ir?",
    "meo_welcome": "¡Bienvenido!",
    "meo_bridged": {
        "start": "Puenteado",
        "title": "Este mensaje ha sido puenteado desde otra plataforma."
    },
    "title_chats": "Chats",
    "title_live": "Tiempo real",
    "settings_general": "General",
    "settings_appearance": "Apariencia",
    "settings_plugins": "Plugins (expansiones)",
    "settings_languages": "Idiomas",
    "general_sub": {
        "chat": "Chat",
        "accessibility": "Accesibilidad",
        "misc": "Otros",
        "acc": "Cuenta",
        "blockedusers": "Usuarios Bloqueados",
        "blockedwords": "Palabras Bloqueadas",
        "about": "Acerca De",
        "credits": "Creditos",
    },
    "general_list": {
        "title": {
            "homepage": "Auto-navegar a Home",
            "consolewarnings": "Desactivar advertencias de la consola",
            "blockedmessages": "Hide blocked user messages",
            "invtyping": "Escritura/Tecleado invisible",
            "imagewhitelist": "Permitir imágenes de cualquier fuente",
            "censorwords": "Censurar palabras de la lista negra",
            "embeds": "Incorporaciones especiales",
            "reducemotion": "Reducir movimiento",
            "showpostbuttons": "Siempre mostrar botones en mensajes",
            "underlinelinks": "Siempre subrayar enlaces",
            "entersend": "No enviar en Intro/Enter",
            "hideimages": "Ocultar imágenes",
        },
        "desc": {
            "homepage": "En lugar de mostrarte la página de inicio, navegar directamente a home",
            "consolewarnings": "Oculta los mensajes de alerta de la consola",
            "blockedmessages": "Mostrar una advertencia (o) ocultar completamente los mensajes bloqueados",
            "invtyping": "Otros usuarios no te verán teclear",
            "imagewhitelist": "Esto permite que cualquier sitio vea tu direction IP, use responsibly",
            "censorwords": "Censurar palabras en lugar de tratarlas como un mensaje bloqueado",
            "embeds": "Incoroporar GIFs de Tenor, Videos de Youtube, ect. (Usa cookies de 3ª part)",
            "reducemotion": "Reducir la intensidad de las animaciones y otros efectos con movimiento",
            "showpostbuttons": "Los botones en las publicaciónes/mensajes permanecen siempre visibles",
            "underlinelinks": "Subrayar los enlaces a sitios web y otras páginas para que destaquen más.",
            "entersend": "La tecla Intro crea nuevas líneas en lugar de enviar el mensaje",
            "hideimages": "Difuminar imágenes antes de abrirlas",
        }
    },
    "appearance_sub": {
        "theme": "Tema",
        "spthemes": "Temas Speciales",
        "acthemes": "Temas Accesibles",
        "ogthemes": "Temas Originales",
        "glthemes": "Temas de Vidrio",
        "cstheme": "Tema Personalizado",
        "cscss": "Código CSS personalizado",
    },
    "plugins_sub": {
        "manage": "Manage",
        "desc": "The plugins repo can be found ",
        "link": "here!"
    },
    "languages_sub": {
        "title": "Seleccione un idioma",
        "desc": "¿No ves tu idioma aquí? Ayuda a traducir en",
        "link": "Github!"
    },
    "inbox_sub": {
        "desc": "Las notificaciones aparecen aquí.",
    },
    "live_sub": {
        "desc": "Aquí no se guardan los mensajes."
    },
    "login_sub": {
        "title": "Iniciar sesión",
        "desc": "Este cliente/servicio fue hecho por eri :> - Traducido al español por ether",
        "oldpass": "Contraseña Anterior",
        "newpass": "Contraseña Nueva",
        "agreement": "Términos de servicio y Política de privacidad"
    },
    "leave_sub": {
        "desc": "¿Estás seguro de que quieres irte",
        "end": "?",
    },
    "action": {
        "logout": "Cerrar Sesión",
        "login": "Iniciar Sesión",
        "signup": "Registrarse",
        "search": "Búsqueda",
        "mod": "Moderar",
        "creategc": "Crear Chat (Grupo)",
        "leavegc": "¿Abandonar Chat/Groupo?",
        "dmme": "DM Me :)",
        "invite": "Invitar Personas",
        "gohome": "Ir a Home",
        "cleartokens": "Borrar Fichas de sesión (Tokens)",
        "changepw": "Cambiar Contraseña",
        "clearls": "Borrar Almacenamiento Local",
        "deleteacc": "Eliminar Cuenta",
        "block": "Bloquear",
        "blockuser": "Bloquear Usuario",
        "blockword": "Añadir Palabra a la Lista Negra",
        "run": "Run (Ejecutar)",
        "close": "Cerrar",
        "back": "Atrás",
        "opennewtab": "Abrir En Navegador Web",
        "reply": "Responder",
        "mention": "Mencionar Usuario",
        "report": "Denunciar",
        "delete": "Eliminar",
        "edit": "Editar",
        "share": "Compartir",
        "comment": "Comentar",
        "nick": "Sobrenombre",
        "create": "Crear",
        "reason": "Razón",
        "sendreport": "Enviar Denuncia",
        "yes": "Si",
        "confirm": "Confirmar",
        "update": "Actualizar",
        "go": "Ir",
        "apply": "Aplicar",
        "savetheme": "Save Theme (Salvar Tema)",
        "loadtheme": "Load Theme (Cargar Tema)",
        "resetplugins": "Deshabilitar todo",
        "favorite": "Favoritos",
    },
    "info": {
        "accexists": "¡Nombre de Usuario ya Ocupado!",
        "invaliduser": "¡Nombre de Usuario Inválido!",
        "invalidpass": "¡Contraseña Inválida!",
        "accbanned": "¡Cuenta Vetada!",
        "accdeleted": "¡Cuenta eliminada!",
        "conflict": "Es probable que hayas iniciado una sesión en otro servicio/ciber cliente. Refresque la página y vuelva a iniciar una sesión para continuar.",
        "unknown": "Estado de inicio de sesión desconocido:",
        "chatremoved": "Has sido eliminado del chat/grupo en el que estabas.",
        "passupdate": "Su contraseña ha sido actualizada. Es posible que tenga que volver a iniciar su sesión.",
        "editingpost": "Editando Mensaje:",
        "reportsent": "¡Denuncia enviada!",
        "blockedip": "Dirección IP bloqueada",
        "searchany": "¡Busca cualquier cosa!",
        "cleartokens": "Esto cerrará tu sesión en todas partes",
        "clearls": "Esto cerrará tu sesión.",
        "signup": "Al registrarte aceptas los términos y condiciones de servicio de Meower",
        "tokenscleared": "Fichas de sesión (Session Tokens) eliminadas, tendrá que volver a iniciar sesión",
        "accscheduled": "Cuenta de usuario programada para su eliminación",
        "deletewarn": "Se borrará PARA SIEMPRE (¡Un tiempo muy largo!)",
        "changepwwarn": "Se actualizará de inmediato.",
        "tryagain": "Inténtalo de nuevo",
        "cleared": "¡Borrado!",
        "plugin": "Reinicia ahora para aplicar las nuevas expansiones y sus ajustes.",
    },
    "reports": {
        "spam": "Spam (Basura)",
        "harassment": "Acoso o abuso hacia otras personas",
        "language": "Lenguaje grosero, vulgar (y/o) ofensivo",
        "nsfw": "NSFW (sexual, alcohol, violencia, sangriento, etc.)",
        "scam": "Estafas, hackeos, phishing (y/o) otros contenidos maliciosos",
        "harm": "Amenazas de violencia o daños en el mundo real",
        "illegal": "Actividad ilegal",
        "suicide": "Autolesión/suicidio",
        "age": "Esta persona es demasiado/a joven para usar Meower",
        "other": "Otro",
    },
    "modals": {
        "report": "Denunciar Mensaje",
        "blockword": "Añadir Palabra a la Lista Negra",
        "blockauser": "Block a User (case sensitive)",
        "blockuser": "Bloquear",
        "unblockuser": "Desbloquear",
        "bgimage": "Enlace de Imagen de Fondo (Background Image Link)",
        "blockedip": "Dirección IP bloqueada",
        "cleartokens": "Borrar Fichas de sesión (Tokens)?",
        "changepass": "Cambiar Contraseña",
        "clearls": "Borrar Almacenamiento Local?",
    },
    "profile": {
        "quote": "Cita de perfil",
        "persona": "Personalización",
        "profilecolor": "Color del perfil",
        "profilepic": "Foto de perfil",
    },
    "chats": {
        "members": "Miembros"
    }
}

const es_es = {
    // Spanish translation by ethernet/ethernet0, converted by NotFenixio
    // Last updated 02/06/2024 (dd/mm/yyyy)
    // hey eris, hi josh
    "language": "Español España",
    "page_home": "Inicio",
    "page_start": "Comienzo",
    "page_explore": "Explorar",
    "page_inbox": "Bandeja de entrada",
    "page_settings": "Configuración",
    "meo_username": "Nombre de usuario",
    "meo_password": "Contraseña",
    "meo_messagebox": "¿Qué tienes en mente?",
    "meo_goanywhere": "¿A dónde te gustaría ir?",
    "meo_welcome": "¡Bienvenido!",
    "meo_bridged": {
        "start": "Conectado",
        "title": "Esta publicación ha sido conectada desde otra plataforma."
    },
    "title_chats": "Chats",
    "title_live": "Chat en vivo",
    "settings_general": "General",
    "settings_appearance": "Apariencia",
    "settings_plugins": "Complementos",
    "settings_languages": "Idiomas",
    "general_sub": {
        "chat": "Chat",
        "accessibility": "Accesibilidad",
        "misc": "Misceláneo",
        "acc": "Cuenta",
        "blockedusers": "Usuarios bloqueados",
        "blockedwords": "Palabras en lista negra",
        "about": "Acerca de",
        "credits": "Créditos"
    },
    "general_list": {
        "title": {
            "homepage": "Navegación automática a Inicio",
            "consolewarnings": "Desactivar advertencias de consola",
            "blockedmessages": "Ocultar mensajes de usuarios bloqueados",
            "invtyping": "Escritura invisible",
            "imagewhitelist": "Permitir imágenes de cualquier fuente",
            "censorwords": "Censurar palabras en lista negra",
            "embeds": "Incrustaciones especiales",
            "reducemotion": "Reducir movimiento",
            "showpostbuttons": "Mostrar siempre los botones de publicación",
            "underlinelinks": "Subrayar siempre los enlaces",
            "entersend": "No enviar con Enter",
            "hideimages": "Ocultar imágenes",
        },
        "desc": {
            "homepage": "En lugar de mostrarte la Página de Inicio, serás llevado directamente a Inicio",
            "consolewarnings": "Oculta los mensajes de advertencia de la consola",
            "blockedmessages": "Mostrar una advertencia u ocultar los mensajes completamente",
            "invtyping": "Otros usuarios no verán que estás escribiendo",
            "imagewhitelist": "Esto permite que cualquier sitio vea tu IP, úsalo responsablemente",
            "censorwords": "Censura palabras en lugar de tratarlas como un mensaje bloqueado",
            "embeds": "Incrusta GIFs de Tenor, videos de YouTube, etc. (Usa cookies de terceros)",
            "reducemotion": "Reduce la intensidad de las animaciones y otros efectos en movimiento",
            "showpostbuttons": "Los botones de publicación siempre permanecen visibles",
            "underlinelinks": "Hacer que los enlaces a sitios web y otras páginas resalten más subrayándolos",
            "entersend": "La tecla Enter crea nuevas líneas en lugar de enviar la publicación",
            "hideimages": "Desenfoca las imágenes antes de abrirlas",
        }
    },
    "appearance_sub": {
        "theme": "Tema",
        "spthemes": "Temas especiales",
        "acthemes": "Temas accesibles",
        "ogthemes": "Temas originales",
        "glthemes": "Temas de vidrio",
        "cstheme": "Tema personalizado",
        "cscss": "CSS personalizado"
    },
    "plugins_sub": {
        "manage": "Gestionar",
        "desc": "El repositorio de complementos se puede encontrar ",
        "link": "aquí!"
    },
    "languages_sub": {
        "title": "Seleccionar un idioma",
        "desc": "¿No ves tu idioma aquí? Ayuda a traducir en",
        "link": "Github!"
    },
    "inbox_sub": {
        "desc": "Las notificaciones se muestran aquí."
    },
    "live_sub": {
        "desc": "Los mensajes no se guardarán aquí."
    },
    "login_sub": {
        "title": "Iniciar sesión",
        "desc": "meo por eri, leo por josh",
        "oldpass": "Contraseña antigua",
        "newpass": "Nueva contraseña",
        "agreement": "Términos de uso y Política de privacidad"
    },
    "leave_sub": {
        "desc": "¿Estás seguro de que quieres salir",
        "end": "?",
    },
    "action": {
        "logout": "Cerrar sesión",
        "login": "Iniciar sesión",
        "signup": "Registrarse",
        "search": "Buscar",
        "mod": "Moderar",
        "creategc": "Crear chat",
        "leavegc": "¿Salir del chat?",
        "dmme": "DM Me :)",
        "invite": "Invitar a personas",
        "gohome": "Ir a Inicio",
        "cleartokens": "Borrar tokens",
        "changepw": "Cambiar contraseña",
        "clearls": "Borrar almacenamiento local",
        "deleteacc": "Eliminar cuenta",
        "block": "Bloquear",
        "blockuser": "Bloquear usuario",
        "blockword": "Palabra en lista negra",
        "run": "Ejecutar",
        "close": "Cerrar",
        "back": "Atrás",
        "opennewtab": "Abrir en el navegador",
        "reply": "Responder",
        "mention": "Mencionar",
        "report": "Reportar",
        "delete": "Eliminar",
        "edit": "Editar",
        "share": "Compartir",
        "comment": "Comentar",
        "nick": "Apodo",
        "create": "Crear",
        "reason": "Razón",
        "sendreport": "Enviar reporte",
        "yes": "Sí",
        "confirm": "Confirmar",
        "update": "Actualizar",
        "go": "Ir",
        "apply": "Aplicar",
        "savetheme": "Guardar tema",
        "loadtheme": "Cargar tema",
        "resetplugins": "Deshabilitar todo",
        "favorite": "Favorito",
    },
    "info": {
        "accexists": "¡Nombre de usuario ya tomado!",
        "invaliduser": "¡Nombre de usuario inválido!",
        "invalidpass": "¡Contraseña inválida!",
        "accbanned": "¡Cuenta bloqueada!",
        "accdeleted": "¡Cuenta eliminada!",
        "conflict": "Probablemente iniciaste sesión en otro cliente. Refresca la página e inicia sesión nuevamente para continuar.",
        "unknown": "Estado de inicio de sesión desconocido:",
        "chatremoved": "Has sido eliminado del chat en el que estabas.",
        "passupdate": "¡Tu contraseña ha sido actualizada!",
        "editingpost": "Editando publicación:",
        "reportsent": "¡Reporte enviado!",
        "blockedip": "IP bloqueada",
        "searchany": "¡Busca cualquier cosa!",
        "cleartokens": "Esto cerrará tu sesión en todas partes.",
        "clearls": "Esto cerrará tu sesión.",
        "signup": "Al registrarte aceptas los Términos de Servicio de Meower",
        "tokenscleared": "Tokens eliminados, necesitarás iniciar sesión nuevamente",
        "accscheduled": "Cuenta programada para eliminación",
        "deletewarn": "Se eliminará PARA SIEMPRE (¡un tiempo muy largo!)",
        "changepwwarn": "Se actualizará inmediatamente.",
        "tryagain": "Inténtalo de nuevo",
        "cleared": "¡Borrado!",
        "plugin": "Reinicia ahora para aplicar los nuevos complementos y sus configuraciones"
    },
    "reports": {
        "spam": "Spam",
        "harassment": "Acoso o abuso hacia otros",
        "language": "Lenguaje grosero, vulgar u ofensivo",
        "nsfw": "NSFW (sexual, alcohol, violencia, gore, etc.)",
        "scam": "Estafas, hacks, phishing u otro contenido malicioso",
        "harm": "Amenaza de violencia o daño real",
        "illegal": "Actividad ilegal",
        "suicide": "Auto-lesiones/suicidio",
        "age": "Esta persona es demasiado joven para usar Meower",
        "other": "Otro"
    },
    "modals": {
        "report": "Reportar publicación",
        "blockword": "Añadir una palabra a la lista negra",
        "blockauser": "Bloquear a un usuario (sensible a mayúsculas)",
        "blockuser": "Bloquear",
        "unblockuser": "Desbloquear",
        "bgimage": "Enlace de imagen de fondo",
        "blockedip": "IP bloqueada",
        "cleartokens": "¿Borrar tokens?",
        "changepass": "Cambiar contraseña",
        "clearls": "¿Borrar almacenamiento local?",
        "deleteacc": "¿Eliminar cuenta?",
        "share": "Compartir",
        "plugin": "¡Requiere actualización!",
    },
    "profile": {
        "quote": "Cita",
        "persona": "Personalización",
        "profilecolor": "Color del perfil",
        "profilepic": "Foto de perfil"
    },
    "chats": {
        "members": "Miembros"
    }
}

const de = {
    // credit: mybearworld
    "language": "Deutsch, Deutschland",
    "page_home": "Home",
    "page_start": "Start",
    "page_explore": "Entdecken",
    "page_inbox": "Posteingang",
    "page_settings": "Einstellungen",
    "meo_username": "Benutzername",
    "meo_password": "Passwort",
    "meo_messagebox": "Worüber denkst du nach?",
    "meo_goanywhere": "Wo würdest du gerne hingehen?",
    "meo_welcome": "Willkommen!",
    "meo_bridged": {
        "start": "Extern", // translated as "external" because "überbrückt" would sound really awkward
        "title": "Dieser Post wurde auf einer externen Platform geschickt."
    },
    "settings_general": "Allgemein",
    "settings_appearance": "Aussehen",
    "settings_plugins": "Plugins",
    "settings_languages": "Sprachen",
    "general_sub": {
        "chat": "Chat",
        "accessibility": "Barrierenfreiheit",
        "misc": "Sonstiges",
        "acc": "Konto",
        "blockedusers": "Blockiert",
        "blockedwords": "Verbotene Wörter",
        "about": "Über",
        "credits": "Dankaussagungen",
    },
    "general_list": {
        "title": {
            "homepage": "Automatisch zu Home gehen",
            "consolewarnings": "Konsolenwarnung ausschalten",
            "blockedmessages": "Nachrichten von blockierten Nutzern verstecken",
            "invtyping": "Durchsichtiges Tippen",
            "imagewhitelist": "Bilder von jeder Quelle erlauben",
            "censorwords": "Verbotene Wörter blockieren",
            "embeds": "Besondere Einbettungen",
            "reducemotion": "Bewegung reduzieren",
            "showpostbuttons": "Postknöpfe immer zeigen",
            "underlinelinks": "Links immer unterstreichen",
        },
        "desc": {
            "homepage": "Direkt zu Home navigieren, statt die Startseite anzuzeigen",
            "consolewarnings": "Die Warnmeldung in der Konsole nicht zeigen",
            "blockedmessages": "Nur eine Warnung zeigen, oder die Nachricht komplett verstecken",
            "invtyping": "Andere Nutzer werden dich nicht tippen sehen",
            "imagewhitelist": "Dadurch kann dadurch deine IP-Adresse sehen, nutze das verantwortlich",
            "censorwords": "Zensiert Wörter, statt sie als blockierte Nachricht zu sehen",
            "embeds": "Tenor-GIFS, YouTube-Videos etc. einbetten (Cookies dritter Parteien)",
            "reducemotion": "Die Intensität der Animationen und andere Bewegungseffekte reduzieren",
            "showpostbuttons": "Postknöpfe bleiben immer sichtbar",
            "underlinelinks": "Links zu Websiten und anderen Seiten unterstreichen und damit hervorheben",
        }
    },
    "appearance_sub": {
        "theme": "Aussehen",
        "spthemes": "Besondere Aussehen",
        "acthemes": "Barrierenfreie Aussehen",
        "ogthemes": "Ursprüngliche Aussehen",
        "glthemes": "Glasaussehen",
        "cstheme": "Eigenes Aussehen",
        "cscss": "Eigenes CSS",
    },
    "plugins_sub": {
        "manage": "Einstellen",
        "desc": "The plugins repo can be found ",
        "link": "here!"
    },
    "languages_sub": {
        "title": "Wähle eine Sprache",
        "desc": "Siehst du deine Sprache hier nicht? Übersetze sie auf",
        "link": "Github!"
    },
    "inbox_sub": {
        "desc": "Benachrichtigungen werden hier angezeigt.",
    },
    "live_sub": {
    },
    "login_sub": {
        "title": "Anmelden",
        "desc": "Dieser Client wurde von eri gemacht :>",
        "oldpass": "Altes Passwort",
        "newpass": "Neues Passwort",
        "agreement": "Geschäftsbedingungen und Datenschutzerklärung"
    },
    "leave_sub": {
    },
    "action": {
        "logout": "Abmelden",
        "login": "Anmelden",
        "signup": "Konto erstellen",
        "search": "Suchen",
        "mod": "Moderieren",
        "creategc": "Chat erstellen",
        "dmme": "Schicke mir eine Nachricht :)",
        "invite": "Menschen einladen",
        "gohome": "Zu Home gehen",
        "cleartokens": "Tokens löschen",
        "changepw": "Passwort ändern",
        "clearls": "Lokalen Speicherplatz löschen",
        "deleteacc": "Konto löschen",
        "block": "Blockieren",
        "blockuser": "Nutzer blockieren",
        "blockword": "Wort verbieten",
        "run": "Ausführen",
        "close": "Schließen",
        "back": "Zurück",
        "opennewtab": "Im Browser öffnen",
        "reply": "Antworten",
        "mention": "Ansprechen",
        "report": "Melden",
        "delete": "Löschen",
        "edit": "Bearbeiten",
        "share": "Teilen",
        "comment": "Kommentieren",
        "nick": "Spitzname",
        "create": "Erstellen",
        "reason": "Grund",
        "sendreport": "Meldung senden",
        "yes": "Ja",
        "confirm": "Bestätigen",
        "update": "Aktualisieren",
        "go": "Los",
        "apply": "Übernehmen",
        "savetheme": "Aussehen speichern",
        "loadtheme": "Aussehen laden",
        "resetplugins": "Alles ausschalten",
    },
    "info": {
        "accexists": "Der Benutzername wird schon benutzt!",
        "invaliduser": "Ungültiger Benutzername!",
        "invalidpass": "Ungültiges Passwort!",
        "accbanned": "Konto gebannt!",
        "accdeleted": "Konto gelöscht!",
        "conflict": "Du hast dich vermutlich bei einem anderen Client angemeldet. Lade die Seite neu und melde dich wieder ein, um weiterzumachen.",
        "unknown": "Unbekannter Anmeldestatus:",
        "chatremoved": "Du wurdest von dem Chat, in dem du bist, entfernt.",
        "passupdate": "Dein Passwort wurde aktualisiert!",
        "editingpost": "Post wird bearbeitet:",
        "reportsent": "Meldung wurde gesendet!",
        "blockedip": "Blockierte IP",
        "searchany": "Suche nach irgendetwas!",
        "cleartokens": "Das wird dich überall abmelden.",
        "clearls": "Das wird dich anmelden.",
        "signup": "Wenn du ein Konto erstellst, stimmst du den Nutzungsbedingungen von Meower zu",
        "tokenscleared": "Tokens wurden gelöscht, du musst dich erneut anmelden",
        "accscheduled": "Konto wird gelöscht werden",
        "deletewarn": "Es wird FÜR IMMER (eine sehr lange Zeit!) gelöscht",
        "tryagain": "Versuche es erneut",
        "cleared": "Gelöscht!",
        "plugin": "Jetzt neu laden um neue Plugins und ihre Einstellungen anzuwenden",
    },
    "reports": {
        "spam": "Spam",
        "harassment": "Hassrede oder Missbrauch anderer",
        "language": "Unhöfliche, vulgäre oder Rude, vulgar or anstößige Sprache",
        "nsfw": "NSFW (Sexuelles, Alkohol, Gewalt, Blut, usw.)",
        "scam": "Betrug, Hacks, Phishing oder andere bösartigen Inhalte",
        "harm": "Drohung von Gewalt oder Schaden",
        "illegal": "Illegale Aktivität",
        "suicide": "Selbstschaden, Suizid",
        "age": "Diese Person ist zu jung, um Meower zu benutzen",
        "other": "Anderes",
    },
    "modals": {
        "report": "Post melden",
        "blockword": "Ein Wort verbieten",
        "blockauser": "Einen User blockieren (Groß- und Kleinschreibung zählt)",
        "blockuser": "Blockieren",
        "unblockuser": "Blockierung aufheben",
        "bgimage": "Link von Hintergrundbild",
        "blockedip": "IP-Blockiert",
        "cleartokens": "Tokens löschen?",
        "changepass": "Passwort ändern",
        "clearls": "Lokalen Speicherplatz löschen?",
        "deleteacc": "Konto löschen?",
        "share": "Teilen",
        "plugin": "Aktualisierung benötigt!",
    },
    "profile": {
        "quote": "Zitat",
        "persona": "Personalisierung",
        "profilecolor": "Profilfarbe",
        "profilepic": "Profilbild",
    }
}

const eh = {
    "language": "Enchantment Table",
    "page_home": "⍑𝙹ᒲᒷ",
    "page_start": "↸╎ᓭᓵ𝙹⍊ᒷ∷",
    "page_explore": "↸╎ᓭᓵ𝙹⍊ᒷ∷",
    "page_inbox": "リ𝙹ℸ╎⎓╎ᓵᔑℸ╎𝙹リᓭ",
    "page_settings": "ᓭᒷℸℸ╎リ⊣ᓭ",
    "meo_username": "ᒷᒲᔑ╎ꖎ",
    "meo_password": "!¡ᔑᓭᓭ∴𝙹∷↸",
    "meo_messagebox": "ᒲᒷᓭᓭᔑ⊣ᒷ",
    "meo_goanywhere": "ᓭᒷᔑ∷ᓵ⍑",
    "meo_welcome": "∴ᒷꖎᓵ𝙹ᒲᒷ!",
    "meo_bridged": {
    },
    "title_chats": "⊣∷𝙹⚍!¡",
    "title_live": "𝙹!¡ᒷリ⊣∷𝙹⚍",
    "settings_general": "⚍ᓭᒷ∷ ᓭᒷℸℸ╎リ⊣ᓭ",
    "settings_appearance": "ᔑ!¡!¡ᒷᔑ∷ᔑリᓵᒷ",
    "settings_languages": "ꖎᔑリ⊣⚍ᔑ⊣ᒷ",
    "general_sub": {
        "chat": "⊣∷𝙹⚍",
    },
    "general_list": {
        "title": {
        },
        "desc": {
        }
    },
    "appearance_sub": {
    },
    "plugins_sub": {
    },
    "languages_sub": {
    },
    "inbox_sub": {
    },
    "live_sub": {
    },
    "login_sub": {
    },
    "leave_sub": {
    },
    "action": {
        "create": "ᓵ∷ᒷᔑℸᒷ",
    },
    "info": {
    },
    "reports": {
    },
    "modals": {
    },
    "profile": {
    },
    "chats": {
    }
}

const b = {
    "language": "Bottom",
    "page_home": "💖✨✨✨,,,👉👈💖💖,👉👈💖💖🥺,,,👉👈💖💖,👉👈💖✨✨✨✨🥺,,,,👉👈💖💖✨🥺,👉👈✨✨✨,,",
    "page_start": "👉👈💖✨✨✨✨🥺,,,,👉👈💖💖✨🥺,👉👈✨✨✨,,",
    "page_explore": "👉👈💖✨✨✨✨🥺,,,,👉👈💖💖✨🥺,",
    "page_inbox": "👉👈💖✨✨✨✨🥺,,,,👉👈💖💖✨🥺,👉👈💖✨✨✨✨🥺,,,,👉👈💖💖✨🥺,👉👈✨✨✨,,",
    "page_settings": "💖✨✨✨,,,👉👈💖💖,👉👈💖💖🥺,,,👉👈💖💖,👉👈💖",
    "meo_username": "👉👈💖💖✨🥺,👉👈💖✨✨✨✨🥺",
    "meo_password": "👉👈💖✨✨✨✨🥺",
    "meo_messagebox": "👉👈💖✨✨✨✨🥺",
    "meo_goanywhere": "💖✨✨✨,,,👉👈💖💖,👉👈💖💖🥺,,,",
    "meo_welcome": "👉👈💖✨✨✨✨🥺!",
    "meo_bridged": {
        "start": "👉👈💖✨",
        "title": "💖✨✨✨,,,👉👈💖💖,👉👈💖💖🥺,,,👉👈💖💖,👉👈💖"
    },
    "title_chats": "💖✨✨✨,,,👉👈💖💖,",
    "title_live": "💖✨✨✨,,,👉👈💖💖,👉👈💖💖🥺,,,👉👈💖💖,👉👈💖",
    "settings_general": "👉👈💖✨✨✨✨🥺",
    "settings_appearance": "💖✨✨,,,👉👈✨💖💖,👉👈💖💖🥺,,,👉👈💖💖,👉👈💖",
    "settings_plugins": "👉👈💖💖🥺,,,👉👈💖💖,👉👈💖",
    "settings_languages": "👉👈💖💖🥺,,,👉👈💖💖,",
    "general_sub": {
        "chat": "👉👈💖💖🥺,,,👉👈💖💖,👉👈💖",
        "accessibility": "👉👈💖💖🥺,,,👉👈💖💖,👉👈💖",
        "misc": "💖✨✨✨,,,👉👈💖💖",
        "acc": "💖✨✨✨,,,👉👈💖💖,👉👈💖💖🥺,,,👉👈💖💖,",
        "blockedusers": "💖✨✨✨,,,👉👈💖💖,👉👈",
        "blockedwords": "💖✨✨,,",
        "about": "💖",
        "credits": "✨",
        "contrib": "👉👈",
        "privacy": "🥺",
    },
    "general_list": {
        "title": {
            "homepage": "💖✨✨✨,,,👉👈💖💖,",
            "consolewarnings": ",👉👈💖💖✨👉👈💖💖✨🥺👉👈",
            "blockedmessages": "💖✨✨✨,,,💖✨✨✨,,,👉👈💖💖,",
            "invtyping": "💖✨✨✨,,,💖✨",
            "imagewhitelist": "👉👈💖💖🥺,,,👉👈💖💖,👉👈💖",
            "censorwords": "💖✨✨✨,,,👉👈💖💖,👉👈💖",
            "embeds": ",,,👉👈💖💖,👉👈💖",
            "reducemotion": "👉👈💖💖🥺,,,👉👈💖💖,👉👈",
            "showpostbuttons": "✨✨,,,👉👈💖💖,👉👈💖",
            "underlinelinks": "💖💖🥺,,,👉👈💖💖",
            "magnify": "💖✨✨✨✨🥺,,,,👉👈💖💖✨🥺,👉👈",
            "entersend": "🥺🥺✨✨",
            "hideimages": "💖💖💖💖",
            "notifications": "👉👈👉👈👉👈👉👈👉👈",
            "widemode": "✨✨✨✨",
            "discord": ",,,👉👈💖💖,👉👈💖",
        },
        "desc": {
            "homepage": "👉👈💖✨✨✨✨🥺",
            "consolewarnings": "✨✨✨,,,👉👈💖💖,👉👈💖💖🥺,,,",
            "blockedmessages": "✨✨✨🥺,,,,👉👈💖",
            "invtyping": "✨,,,👉👈💖💖,👉👈💖💖🥺,",
            "imagewhitelist": ",👉👈💖💖✨🥺,👉👈💖✨✨✨✨🥺,,,,👉👈💖💖✨🥺,👉👈✨",
            "censorwords": "✨,,,👉👈✨💖💖,👉👈💖💖🥺,,,👉👈💖💖,👉",
            "embeds": ",👉👈✨💖💖,👉👈💖💖🥺,,,👉👈💖",
            "reducemotion": "✨✨✨🥺,,,,👉👈💖💖✨🥺,👉👈",
            "showpostbuttons": "✨💖💖,👉👈💖💖🥺,,,👉👈💖",
            "underlinelinks": "✨,,,👉👈✨💖💖,👉👈💖💖🥺,,,👉👈💖💖,",
            "magnify": "💖✨🥺,👉👈💖✨✨✨✨🥺,,,,",
            "entersend": "👈💖💖✨👉👈💖💖✨🥺👉",
            "hideimages": "👉👈✨💖💖,👉👈💖💖🥺,,,👉👉👈✨👉👈✨💖💖,,,,👉,👉👈💖💖🥺",
            "notifications": "👉👈👉👈👉👈👉👈👉👈👉👈👉👈👉👈👉👈👉👈",
            "widemode": "✨✨,,,👉👈💖💖,👉👈",
            "discord": "👉👈💖💖🥺,,,👉👈💖💖,👉👈👉👈💖💖🥺,,,👉👈💖💖,👉👈",
        }
    },
    "appearance_sub": {
        "theme": "💖✨✨✨",
        "spthemes": "👉👈✨💖💖",
        "acthemes": "💖💖✨👉👈",
        "ogthemes": "✨💖👉👈",
        "glthemes": "🥺✨👉🎈",
        "cstheme": "👉👈✨💖",
        "cscss": "💖✨👉👈",
    },
    "plugins_sub": {
        "manage": "👉👈💖✨🥺",
        "desc": "✨👉👈💖💖💖💖",
        "link": "💖✨👉👈!"
    },
    "languages_sub": {
        "title": "💖✨👉👈💖💖",
        "desc": "🥺💖👉👈✨✨",
        "link": "💖👉👈!",
        "other": "👉👈💖✨🥺"
    },
    "inbox_sub": {
        "desc": "👉👈✨💖💖💖💖.",
    },
    "live_sub": {
        "desc": "💖✨💖👉👈💖💖."
    },
    "login_sub": {
        "title": "💖✨👉👈",
        "desc": "👉👈💖✨💖💖💖",
        "oldpass": "👉👈💖✨",
        "newpass": "✨👉👈💖",
        "agreement": "💖✨💖💖✨💖",
    },
    "leave_sub": {
        "desc": "👉👈💖💖👉👈💖",
        "end": "✨?",
    },
    "action": {
        "logout": "👉👈💖💖✨",
        "login": "💖✨👉👈",
        "signup": "💖💖👉👈💖",
        "search": "💖✨👉👈",
        "mod": "💖✨💖👉👈",
        "creategc": "💖💖✨👉👈💖",
        "leavegc": "🎈💖💖💖💖?",
        "dmme": "💖👉👈💖💖✨",
        "invite": "💖👉👈💖💖💖",
        "gohome": "💖✨💖💖👉👈",
        "cleartokens": "💖✨💖💖💖💖",
        "changepw": "💖💖✨👉👈",
        "clearls": "👉👈💖✨🦄",
        "deleteacc": "💖✨💖💖💖",
        "block": "😭👉👈💖✨",
        "blockuser": "💖👉👈💖✨💖",
        "blockword": "💖💖👉👈💖💖",
        "run": "💖👉👈💖💖",
        "close": "👉👈💖💖",
        "back": "💖✨👉👈",
        "opennewtab": "✨👉👈💖💖✨",
        "reply": "💖👉👈💖💖✨",
        "mention": "💖✨👉👈",
        "report": "💖💖💖👉👈",
        "delete": "💖✨💖👉👈",
        "edit": "💖✨👉👈💖💖",
        "share": "💖✨👉👈💖✨",
        "comment": "💖✨👉👈💖💖",
        "nick": "💖✨👉👈💖",
        "create": "💖👉👈💖💖",
        "reason": "💖💖✨👉👈",
        "sendreport": "💖✨💖💖👉👈",
        "yes": "💖✨",
        "confirm": "💖✨👉👈",
        "update": "💖✨👉👈💖💖",
        "go": "💖✨👉👈💖💖",
        "apply": "💖✨👉👈💖",
        "savetheme": "💖💖👉👈💖",
        "loadtheme": "💖✨👉👈💖",
        "resetplugins": "💖✨👉👈💖💖",
        "favorite": "💖✨➡️💖💖💖",
        "download": "👉👈💖💖💖💖",
        "add": "💖✨👉👈",
        "adduser": "👍💖💖✨💖",
        "transfer": "💖✨💖👉👈",
        "bug": "💖💖✨👉👈",
        "datarequest": "💖✨👉👈💖💖",
        "discuss": "💖✨👉👈💖💖",
    },
    "info": {
        "accexists": "💖✨💖✨💖💖💖",
        "invaliduser": "💖💖💖✨!",
        "invalidpass": "💖💖💖💖!",
        "invalidcreds": "💖💖✨💖💖!",
        "accbanned": "💖💖💖💖!",
        "accdeleted": "💖💖💖💖💖💖!",
        "conflict": "💖💖💖💖👉👈💖💖💖💖.",
        "unknown": "💖💖💖💖💖💖💖💖:",
        "chatremoved": "👉👈💖💖💖💖💖💖.",
        "passupdate": "💖💖💖💖💖💖!",
        "editingpost": "👉👈💖💖✨💖:",
        "reportsent": "💖💖💖💖!",
        "blockedip": "💖💖💖💖💖💖",
        "searchany": "💖💖👉👈💖💖!",
        "cleartokens": "👉👈💖✨💖✨💖💖",
        "clearls": "💖✨💖💖💖💖💖",
        "signup": "💖💖💖💖💖",
        "tokenscleared": "💖💖✨💖",
        "accscheduled": "💖✨💖💖💖💖",
        "deletewarn": "💖💖💖💖💖💖💖💖👈",
        "changepwwarn": "💖💖💖💖!",
        "tryagain": "💖✨💖💖💖",
        "cleared": "💖✨💖💖💖!",
        "plugin": "💖💖💖💖💖",
    },
    "reports": {
        "spam": "💖✨",
        "harassment": "💖💖👉👈💖💖",
        "language": "💖💖💖💖💖💖",
        "nsfw": "💖💖💖💖💖💖",
        "scam": "💖💖💖💖💖💖",
        "harm": "💖💖💖💖💖💖",
        "illegal": "💖💖💖💖💖💖",
        "suicide": "💖💖💖💖💖💖",
        "age": "💖💖💖💖💖💖",
        "other": "💖💖💖💖",
    },
    "modals": {
        "report": "💖💖💖💖💖",
        "blockword": "💖💖💖💖💖",
        "blockauser": "💖✨👉👈💖💖",
        "blockuser": "💖💖💖💖",
        "unblockuser": "💖💖💖💖",
        "bgimage": "💖💖💖💖💖",
        "blockedip": "💖💖💖💖💖💖",
        "cleartokens": "💖💖💖💖?",
        "changepass": "💖✨💖💖💖",
        "clearls": "💖💖💖💖💖?",
        "deleteacc": "💖💖💖💖?",
        "share": "💖💖💖💖",
        "plugin": "💖💖💖💖💖!",
        "shortcuts": "💖💖💖💖💖✨",
        "copyuser": "💖💖💖💖💖💖💖!",
    },
    "profile": {
        "quote": "💖✨💖",
        "persona": "💖✨",
        "profilecolor": "💖💖",
        "profilepic": "💖✨💖",
    },
    "chats": {
        "owner": "💖💖💖💖",
        "members": "💖💖💖💖💖"
    }
}

const owo = {
    "language": "uwu",
    "page_home": "howome",
    "page_start": "Stawt",
    "page_explore": "Expwowe",
    "page_inbox": "Inbwox",
    "page_settings": "Settings~",
    "meo_username": "Usenamwwe",
    "meo_password": "Passwowrd",
    "meo_messagebox": "W-What's on youw mind? ^ω^",
    "meo_goanywhere": "W-Where wouwd you wike to go? >w<",
    "meo_welcome": "Wewcome! ^^",
    "meo_bridged": {
        "start": "Bwidged",
        "title": "This post has been bwidged fwom anothew pwatform. UwU"
    },
    "title_chats": "Chats~",
    "title_live": "Wivechat~",
    "settings_general": "Genaewal",
    "settings_appearance": "Appeawance~",
    "settings_plugins": "Pwugins~",
    "settings_languages": "Wanguages~",
    "general_sub": {
        "chat": "Chat~",
        "accessibility": "Accessibiwity~",
        "misc": "Miscellaneous~",
        "acc": "Account~",
        "blockedusers": "Bwocks~",
        "blockedwords": "Bwackwisted W-words~",
        "about": "About~",
        "credits": "Cwedit~",
        "contrib": "Contwibute~",
        "privacy": "Pwivacy & Safety~",
    },
    "general_list": {
        "title": {
            "homepage": "Auto-navigate to Hoom~",
            "consolewarnings": "Disable console wowning~",
            "blockedmessages": "Hide bwocked usew messages~",
            "invtyping": "Invisible typing~",
            "imagewhitelist": "Allow images fwom any souwce~",
            "censorwords": "Censow bwackwisted w-words~",
            "embeds": "Speciaw embeds~",
            "reducemotion": "Wewuce motion~",
            "showpostbuttons": "Always show post buttows~",
            "underlinelinks": "Always undeewine winks~",
            "magnify": "Magnify text~",
            "entersend": "Don't send on Entew~",
            "hideimages": "Hide images~",
            "notifications": "Allow Notifications~",
            "widemode": "New Desktop Expewience~",
            "discord": "Discord Post Wayout~",
        },
        "desc": {
            "homepage": "Instead of showing you the Stawt Page you get diwectwy taken to hoom~",
            "consolewarnings": "Hides wowning message fwom console~",
            "blockedmessages": "Show a wowning or hide messages compwetewy~",
            "invtyping": "Other usews won't see you typing~",
            "imagewhitelist": "This allows any site to see youw IP, use wesponsibwy~",
            "censorwords": "Censows w-words instead of tweating them wike a bwocked message~",
            "embeds": "Embeds Tenow GIFS, Youtube Videos, etc. (Uses 3rd pawty cookies)~",
            "reducemotion": "Wewuce the intensity of animations and other moving effects~",
            "showpostbuttons": "Post buttons always wemain visible~",
            "underlinelinks": "Make winks to websites and other pages stand out mowe by undewwining them~",
            "magnify": "Enwargens and bows text to be easiew to wead with poor eyesight (Wequiwes wefwesh)~",
            "entersend": "Entew key cweates newwines instead of sending the post~",
            "hideimages": "Bwuws images befowe opening them~",
            "notifications": "This will ask fow notification pewmissions (Expwimentaw)~",
            "widemode": "Enabwes new desktop expewience (Expwimentaw, Wequiwes wefwesh)~",
            "discord": "Wevewses the post owdew to be mowe wike Discord (Expwimentaw, Wequiwes wefwesh)~",
        }
    },
    "appearance_sub": {
        "theme": "Theme~",
        "spthemes": "Speciaw Themes~",
        "acthemes": "Accessibwe Themes~",
        "ogthemes": "Owiginaw Themes~",
        "glthemes": "Gwass Themes~",
        "cstheme": "Custom Theme~",
        "cscss": "Custom CSS~",
    },
    "plugins_sub": {
        "manage": "Manage~",
        "desc": "The pwugins wepo can be found ",
        "link": "hewe!"
    },
    "languages_sub": {
        "title": "Select a Wanguage~",
        "desc": "Don't see youw wanguage hewe? Hewp twanswate on ",
        "link": "Github!",
        "other": "Other Wanguages~"
    },
    "inbox_sub": {
        "desc": "Notifications awe dispwayed hewe~",
    },
    "live_sub": {
        "desc": "Messages won't be saved hewe~"
    },
    "login_sub": {
        "title": "Login~",
        "desc": "This client was made by ewi :>",
        "oldpass": "Owd Passwowrd~",
        "newpass": "New Passwowrd~",
        "agreement": "Terms of Use & Pwivacy Powicy~",
    },
    "leave_sub": {
        "desc": "Awe you suwe you want to weave~",
        "end": "?",
    },
    "action": {
        "logout": "Log Out~",
        "login": "Log In~",
        "signup": "Wegistew~",
        "search": "Seawch~",
        "mod": "Modewate~",
        "creategc": "Cweate Chat~",
        "leavegc": "Weave Chat?~",
        "dmme": "DM Me :)~",
        "invite": "Invite Peopwe~",
        "gohome": "Go Hoom~",
        "cleartokens": "Cwear Tokens?~",
        "changepw": "Change Passwowrd~",
        "clearls": "Cweaw Locawstowage?~",
        "deleteacc": "Delete Account?~",
        "block": "Bwock~",
        "blockuser": "Bwock Usew~",
        "blockword": "Bwackwist W-Word~",
        "run": "Wun~",
        "close": "Cwose~",
        "back": "Back~",
        "opennewtab": "Open in Bwowsew~",
        "reply": "Wepwy~",
        "mention": "Mention~",
        "report": "Wepowt~",
        "delete": "Delete~",
        "edit": "Edit~",
        "share": "Shawe~",
        "comment": "Comment~",
        "nick": "Nickname~",
        "create": "Cweate~",
        "reason": "Weason~",
        "sendreport": "Send Wepowt~",
        "yes": "Yas~",
        "confirm": "Confwim~",
        "update": "Update~",
        "go": "Go~",
        "apply": "Appwy~",
        "savetheme": "Save Theme~",
        "loadtheme": "Load Theme~",
        "resetplugins": "Disabwe Aww~",
        "favorite": "Favoowite~",
        "download": "Download~",
        "add": "Add~",
        "adduser": "Add Membeow~", // update
        "transfer": "Twansfew Ownewship~", // update
        "bug": "Wepowt Bug~", // update
        "datarequest": "Wequest Data~", // update
        "discuss": "Discuss~", // update
    },
    "info": {
        "accexists": "Usename Awweady Taken! >w<",
        "invaliduser": "Invawid Usename! =^.^=",
        "invalidpass": "Invawid Passwowrd! >_<",
        "invalidcreds": "Invawid usename ow passwowrd! T_T",
        "accbanned": "Account Banned! UwU",
        "accdeleted": "Account Deweeted! T^T",
        "conflict": "You pwobabwy wogged in on anothew client. Wefwesh the page and log back in to continue~",
        "unknown": "Unknown Login Status: o.o",
        "chatremoved": "You have been wemoved fwom the chat you wewe in~",
        "passupdate": "Youw passwowd has been updated! UwU",
        "editingpost": "Editing Post: >w<",
        "reportsent": "Wepowt Sent! UwU",
        "blockedip": "Bwocked IP >_<",
        "searchany": "Seawch fow anything~!",
        "cleartokens": "This will log you out evewywhewe~.",
        "clearls": "This will log you out~.",
        "signup": "By signing up you agwee to the Meower TOS~",
        "tokenscleared": "Tokens deweted, you wiww need to log back in~",
        "accscheduled": "Account scheduwed fow deweteion~",
        "deletewarn": "It wiww be deweted FOWEVEW (a vewy wong time!)~",
        "changepwwarn": "It wiww be updated immediatewy~.",
        "tryagain": "Twy again! >w<",
        "cleared": "Cweared! :3",
        "plugin": "Westaht now to appwy new pwugins and theiw settings~",
    },
    "reports": {
        "spam": "Spam~",
        "harassment": "Hawassment ow abuse towawds othews~",
        "language": "Wude, vuowgar ow offensive wanguage~",
        "nsfw": "NSFW (sexuaw, awcohow, viowence, gowe, etc.)~",
        "scam": "Scams, hacks, phishing ow othew mawicious content~",
        "harm": "Thweatening viowence ow weaw wowwd harm~",
        "illegal": "Iwegal activity~",
        "suicide": "Sewf-hawm/suicide~",
        "age": "This pewson is too young to use Meower~",
        "other": "Othew~",
    },
    "modals": {
        "report": "Wepowt Post~",
        "blockword": "Bwackwist a W-Word~",
        "blockauser": "Bwock a Usew (case sensitive)~",
        "blockuser": "Bwock~",
        "unblockuser": "Unbwock~",
        "bgimage": "Backgwound Image Wink~",
        "blockedip": "IP Bwocked! >w<",
        "cleartokens": "Cweaw Tokens?~",
        "changepass": "Change Passwowrd~",
        "clearls": "Cweaw Locawstowage?~",
        "deleteacc": "Delete Account?~",
        "share": "Shawe~",
        "plugin": "Wefwesh Wequiwed! UwU",
        "shortcuts": "Showtcuts~",
        "copyuser": "Copied usename to cwipboard! UwU",
    },
    "profile": {
        "quote": "Quote~",
        "persona": "Peasonawization~",
        "profilecolor": "Pwofile Cowow~",
        "profilepic": "Pwofile Pictuwe~",
    },
    "chats": { // update
        "owner": "Ownership~",
        "members": "Membews~"
    }
}

const pirate = {
    "language": "Pirate Speak (Yarr!)",
    "page_home": "Mainland",
    "page_start": "Set Sail",
    "page_explore": "Explore the Seas",
    "page_inbox": "Message Bottles",
    "page_settings": "Settin's",
    "meo_username": "Crew Username",
    "meo_password": "Secret Code",
    "meo_messagebox": "What be on yer mind, matey?",
    "meo_goanywhere": "Where be ye wantin' to go?",
    "meo_welcome": "Ahoy, Welcome aboard!",
    "meo_bridged": {
        "start": "Bridged",
        "title": "This message be carried over from another port."
    },
    "title_chats": "Maties",
    "title_live": "Live Maties",
    "settings_general": "General",
    "settings_appearance": "Appearance",
    "settings_plugins": "Ship's Plugins",
    "settings_languages": "Languages of the Sea",
    "general_sub": {
        "chat": "Maties",
        "accessibility": "Accessibility",
        "misc": "Miscellaneous Booty",
        "acc": "Account",
        "blockedusers": "Blocked Scallywags",
        "blockedwords": "Cursed Words",
        "about": "About the Crew",
        "credits": "Credits to Me Crew",
        "contrib": "Contribute yer Treasure",
        "privacy": "Privacy & Safety on the High Seas",
    },
    "general_list": {
        "title": {
            "homepage": "Auto-navigate to Home Port",
            "consolewarnings": "Disable console squawks",
            "blockedmessages": "Hide messages from scallywags",
            "invtyping": "Invisible Typin'",
            "imagewhitelist": "Allow images from any port",
            "censorwords": "Censor cursed words",
            "embeds": "Special Embeds",
            "reducemotion": "Reduce Ship's Motion",
            "showpostbuttons": "Always show post buttons",
            "underlinelinks": "Always underline links to treasure",
            "magnify": "Magnify text",
            "entersend": "Don't send on Enter",
            "hideimages": "Hide images behind the plunder",
            "notifications": "Allow Notifications from the Crow's Nest",
            "widemode": "New Desktop Experience Ahoy!",
            "discord": "Discord Post Layout, Yarr!",
        },
        "desc": {
            "homepage": "Instead of showin' ye the Start Page, ye be taken straight to home port",
            "consolewarnings": "Hides squawk from the console",
            "blockedmessages": "Show a warning or hide messages completely from scallywags",
            "invtyping": "Other buccaneers won't see ye typin'",
            "imagewhitelist": "This allows any ship to see yer IP; use responsibly",
            "censorwords": "Censors words instead of treatin' 'em like a blocked message",
            "embeds": "Embeds Tenor GIFs, YouTube Videos, etc. (Uses third-party cookies, Yarr!)",
            "reducemotion": "Reduce the intensity of animations and other moving effects, matey",
            "showpostbuttons": "Post buttons always remain visible fer all hands",
            "underlinelinks": "Make links to treasure maps stand out more by underlinin' 'em",
            "magnify": "Enlargens and bolds text for those with poor eyesight (Requires refresh)",
            "entersend": "Enter key creates newlines instead of sendin' the post",
            "hideimages": "Blurs images before ye open 'em",
            "notifications": "This be asking fer notification permissions (Experimental, Yarr!)",
            "widemode": "Enables new desktop experience (Experimental, Requires refresh, matey!)",
            "discord": "Reverses the post order to be more like Discord (Experimental, Requires refresh)",
        }
    },
    "appearance_sub": {
        "theme": "Ship's Theme",
        "spthemes": "Special Themes of the Seven Seas",
        "acthemes": "Accessible Themes",
        "ogthemes": "Original Pirate Themes",
        "glthemes": "Glass Themes",
        "cstheme": "Custom Ship Theme",
        "cscss": "Custom CSS",
    },
    "plugins_sub": {
        "manage": "Manage Ship's Plugins",
        "desc": "The plugins treasure trove can be found ",
        "link": "here, matey!"
    },
    "languages_sub": {
        "title": "Select a Language of the High Seas",
        "desc": "Don't see yer tongue here? Help translate on",
        "link": "Github!",
        "other": "Other Languages of the Ocean"
    },
    "inbox_sub": {
        "desc": "Notifications be displayed here.",
    },
    "live_sub": {
        "desc": "Messages won't be saved here on the ship."
    },
    "login_sub": {
        "title": "Login to yer Ship",
        "desc": "This client be made by eri :>",
        "oldpass": "Old Secret Code",
        "newpass": "New Secret Code",
        "agreement": "Terms of Use & Privacy Policy of the Sea",
    },
    "leave_sub": {
        "desc": "Are ye sure ye want to leave the ship",
        "end": "?",
    },
    "action": {
        "logout": "Log Out from the Ship",
        "login": "Log In to the Ship",
        "signup": "Join the Crew",
        "search": "Sear'",
        "mod": "Moderate the Seas",
        "creategc": "Create Chat for Buccaneers",
        "leavegc": "Leave the Chat?",
        "dmme": "Send me a Message in a Bottle :)",
        "invite": "Invite More Crew Members",
        "gohome": "Go Home Port",
        "cleartokens": "Clear Tokens and Shanties",
        "changepw": "Change Secret Code",
        "clearls": "Clear Local Storage of the Ship",
        "deleteacc": "Delete Account from the Log",
        "block": "Block a Scallywag",
        "blockuser": "Block User",
        "blockword": "Blacklist Cursed Word",
        "run": "Run like a Scurvy Dog",
        "close": "Close the Porthole",
        "back": "Back to the Deck",
        "opennewtab": "Open in Browser of the Seven Seas",
        "reply": "Reply to the Message in a Bottle",
        "mention": "Mention the Crew",
        "report": "Report to the Captain",
        "delete": "Delete the Message in the Bottle",
        "edit": "Edit the Scroll",
        "share": "Share yer Treasure",
        "comment": "Leave a Mark",
        "nick": "Pirate Name",
        "create": "Create a Treasure Map",
        "reason": "Reason for the Action",
        "sendreport": "Send Report to the Captain",
        "yes": "Aye",
        "confirm": "Confirm yer Action",
        "update": "Update the Logs",
        "go": "Set Sail",
        "apply": "Apply the Changes",
        "savetheme": "Save the Ship's Theme",
        "loadtheme": "Load the Ship's Theme",
        "resetplugins": "Disable All Plugins",
        "favorite": "Favorite Treasure",
        "download": "Download Booty",
        "add": "Add to the Crew",
        "adduser": "Add Crew Member",
        "transfer": "Transfer Ownership of the Ship",
        "bug": "Report Bug in the Ship's Code",
        "datarequest": "Request yer Data",
        "discuss": "Discuss Strategy",
    },
    "info": {
        "accexists": "Username Already Taken by Other Crew!",
        "invaliduser": "Invalid Username, ye scallywag!",
        "invalidpass": "Invalid Secret Code!",
        "invalidcreds": "Invalid username or secret code!",
        "accbanned": "Account Banned by the Highsea Council!",
        "accdeleted": "Account Deleted from the Log!",
        "conflict": "Ye probably logged in on another ship. Refresh the page and log back in to continue.",
        "unknown": "Unknown Login Status on the Captain's Log:",
        "chatremoved": "Ye have been removed from the chat ye were in.",
        "passupdate": "Yer secret code has been updated, matey!",
        "editingpost": "Editing Scroll:",
        "reportsent": "Report Sent to the Captain!",
        "blockedip": "Blocked IP on the Ship",
        "searchany": "Search for any buried treasure!",
        "cleartokens": "This will log ye out everywhere, scallywag.",
        "clearls": "This will log ye out, matey.",
        "signup": "By signin' up ye agree to the Meower TOS",
        "tokenscleared": "Tokens deleted, ye will need to log back in",
        "accscheduled": "Account scheduled for deletion from the Log",
        "deletewarn": "It will be deleted FOREVER (a long time in Davy Jones' locker!)",
        "changepwwarn": "It will be updated immediately, matey.",
        "tryagain": "Try again, matey!",
        "cleared": "Cleared, Yarr!",
        "plugin": "Restart now to apply new plugins and their settings, matey!",
    },
    "reports": {
        "spam": "Spam on the Waves",
        "harassment": "Harassment or abuse towards other buccaneers",
        "language": "Rude, vulgar or offensive lingo",
        "nsfw": "NSFW (With rum, sirens, violence, or gore)",
        "scam": "Scams, hacks, phishing, or other foul business",
        "harm": "Threatening violence or real-world harm, Yarr!",
        "illegal": "Illegal activity on the high seas",
        "suicide": "Self-harm/suicidal thoughts, matey!",
        "age": "This young matey be too young to sail Meower seas",
        "other": "Other Scallywag Behaviors",
    },
    "modals": {
        "report": "Report the Post to the Captain",
        "blockword": "Blacklist a Cursed Word",
        "blockauser": "Block a User (case-sensitive, matey)",
        "blockuser": "Block",
        "unblockuser": "Unblock",
        "bgimage": "Background Image Link to Treasure Map",
        "blockedip": "IP Blocked from the Ship",
        "cleartokens": "Clear Tokens, Yarr?",
        "changepass": "Change Yer Secret Code",
        "clearls": "Clear Local Storage of the Ship?",
        "deleteacc": "Delete Account from the Ship?",
        "share": "Share with the Crew",
        "plugin": "Refresh Required fer the Ship!",
        "shortcuts": "Ship's Shortcuts",
        "copyuser": "Copied username to yer treasure chest!",
    },
    "profile": {
        "quote": "Quote from the Sea",
        "persona": "Personalization of the Pirate",
        "profilecolor": "Profile Color of the Ship",
        "profilepic": "Profile Picture of the Captain",
    },
    "chats": {
        "owner": "Ship Ownership",
        "members": "Crew Members"
    }
}

const cowboy = {
    "language": "American (Traditional)",
    "page_home": "Home Sweet Home",
    "page_start": "Giddy Up!",
    "page_explore": "Roundup the Good Stuff",
    "page_inbox": "Holler Box",
    "page_settings": "Hitchin' Post",
    "meo_username": "Brand Name",
    "meo_password": "Secret Key",
    "meo_messagebox": "What’s on yer mind, cowboy?",
    "meo_goanywhere": "Where to next, partner?",
    "meo_welcome": "Welcome, Buckaroo!",
    "meo_bridged": {
        "start": "Tied Together",
        "title": "This here post was tied together from another camp."
    },
    "title_chats": "Chit Chats",
    "title_live": "Roundup Talk",
    "settings_general": "General Wrangler",
    "settings_appearance": "Lookin' Fine",
    "settings_plugins": "Sidekicks",
    "settings_languages": "Languages Roundup",
    "general_sub": {
        "chat": "Chat",
        "accessibility": "Accessible Range",
        "misc": "Miscellaneous Sundries",
        "acc": "Account",
        "blockedusers": "Blocked Rustlers",
        "blockedwords": "Wanted Words",
        "about": "About Us",
        "credits": "Cowpoke Credits",
        "contrib": "Contribute to the Herd",
        "privacy": "Privacy & Safety Roundup",
    },
    "general_list": {
        "title": {
            "homepage": "Auto-navigate to Home Base",
            "consolewarnings": "Hide the Warning Yells",
            "blockedmessages": "Hide Rustler Messages",
            "invtyping": "Typing in Quiet Mode",
            "imagewhitelist": "Allow Pictures from Any Ranch",
            "censorwords": "Muzzle the Wanted Words",
            "embeds": "Special Ranch Embeds",
            "reducemotion": "Calm the Ponies (Reduce Motion)",
            "showpostbuttons": "Always Show Post Buttons",
            "underlinelinks": "Underline the Trail Markers",
            "magnify": "Enlarge the Text",
            "entersend": "Pressin’ Enter Don’t Send",
            "hideimages": "Hide Images 'til You’re Ready",
            "notifications": "Allow the Yellin' Notifications",
            "widemode": "New Desktop Roundup",
            "discord": "Upside Down Post Layout",
        },
        "desc": {
            "homepage": "Skip the Start Page and head straight to Home Base",
            "consolewarnings": "Hides the warning hollers from the console",
            "blockedmessages": "Show a warning or hide those messages completely",
            "invtyping": "Others won’t see ya typin’",
            "imagewhitelist": "This lets any site see yer IP, use wisely, partner!",
            "censorwords": "Censors words instead of treatin' 'em like a blocked message",
            "embeds": "Embeds Tenor GIFS, Youtube Videos, etc. (Requires third-party cookies)",
            "reducemotion": "Reduces the intensity of animations and other movin’ effects",
            "showpostbuttons": "Post buttons always stay visible",
            "underlinelinks": "Make links stand out more by underlining 'em",
            "magnify": "Makes the text bigger and bolder for easy readin’",
            "entersend": "Enter key creates newlines instead of sendin' the post",
            "hideimages": "Blurs images before ya open 'em",
            "notifications": "This will ask fer notification permissions (Experimental)",
            "widemode": "Enables new desktop roundup (Requires refresh)",
            "discord": "Reverses post order to be more like Discord (Experimental, Requires refresh)",
        }
    },
    "appearance_sub": {
        "theme": "Theme",
        "spthemes": "Special Themes",
        "acthemes": "Accessible Themes",
        "ogthemes": "Original Themes",
        "glthemes": "Glass Themes",
        "cstheme": "Custom Theme",
        "cscss": "Custom CSS",
    },
    "plugins_sub": {
        "manage": "Wrangle 'Em",
        "desc": "The plugins corral can be found ",
        "link": "right here, partner!"
    },
    "languages_sub": {
        "title": "Select a Dialect",
        "desc": "Don’t see yer lingo here? Help translate over on",
        "link": "Github, cowboy!",
        "other": "Other Lingos"
    },
    "inbox_sub": {
        "desc": "All yer notifications are displayed here."
    },
    "live_sub": {
        "desc": "Messages ain’t saved here, partner."
    },
    "login_sub": {
        "title": "Login",
        "desc": "This here client was conjured up by eri :>",
        "oldpass": "Old Secret Key",
        "newpass": "New Secret Key",
        "agreement": "Terms of Use & Privacy Policy (Yer Agreement)",
    },
    "leave_sub": {
        "desc": "Are ya sure ya wanna ride off",
        "end": "?"
    },
    "action": {
        "logout": "Saddle Up & Log Out",
        "login": "Mount Up & Log In",
        "signup": "Join the Roundup",
        "search": "Scout",
        "mod": "Wrangle Moderation",
        "creategc": "Start a Powwow",
        "leavegc": "Skedaddle from the Chat?",
        "dmme": "Send Me a Message :)",
        "invite": "Ranch Invites",
        "gohome": "Ride Home",
        "cleartokens": "Clear Tokens, partner?",
        "changepw": "Change Secret Key",
        "clearls": "Clear Localstorage?",
        "deleteacc": "Delete Account?",
        "block": "Block Rustler",
        "blockuser": "Block User",
        "blockword": "Blacklist a Word",
        "run": "Get Along",
        "close": "Shut 'er Down",
        "back": "Backtrack",
        "opennewtab": "Open in Browser (For a Better View)",
        "reply": "Reply Back",
        "mention": "Give a Shoutout",
        "report": "Report a Misbehavin’ Post",
        "delete": "Delete It",
        "edit": "Tweak It",
        "share": "Share the Love",
        "comment": "Leave a Note",
        "nick": "Nickname the Ol' Trail Pal",
        "create": "Forge Ahead & Create",
        "reason": "Give Us a Reason",
        "sendreport": "Send the Report",
        "yes": "Yep!",
        "confirm": "Confirm It",
        "update": "Update It",
        "go": "Giddy Up!",
        "apply": "Apply Now",
        "savetheme": "Save Yer Theme",
        "loadtheme": "Load That Theme",
        "resetplugins": "Shut 'Em All Down",
        "favorite": "Favorite It",
        "download": "Download the Goods",
        "add": "Add to the Herd",
        "adduser": "Add a New Member", 
        "transfer": "Transfer Ownership", 
        "bug": "Report a Bug Out on the Range", 
        "datarequest": "Request Data (Yeehaw)", 
        "discuss": "Let’s Chew the Fat", 
    },
    "info": {
        "accexists": "That Brand Name’s Already Taken!",
        "invaliduser": "That’s an Invalid Brand Name!",
        "invalidpass": "That’s Some Invalid Secret Key!",
        "invalidcreds": "Invalid brand name or secret key!",
        "accbanned": "Account Banned, partner!",
        "accdeleted": "Account Deleted – Gone for Good!",
        "conflict": "Looks like ya logged in on another camp. Refresh the page an’ log back in to continue.",
        "unknown": "Unknown Login Status, partner:",
        "chatremoved": "Ya’ve been removed from the chat you were in.",
        "passupdate": "Yer secret key has been updated!",
        "editingpost": "Editin’ Post:",
        "reportsent": "Report Sent, cowpoke!",
        "blockedip": "Blocked Your IP, partner!",
        "searchany": "Search for anything under the sun!",
        "cleartokens": "This will log ya out everywhere.",
        "clearls": "This will log ya out.",
        "signup": "By joinin' the herd, you agree to the Meower TOS",
        "tokenscleared": "Tokens cleared, you’ll need to log back in.",
        "accscheduled": "Account scheduled fer deletion",
        "deletewarn": "It’ll be deleted FOREVER (and that’s a long time, partner!)",
        "changepwwarn": "It will update right quick.",
        "tryagain": "Give it another shot",
        "cleared": "Cleared Out!",
        "plugin": "Restart now to apply them plugins and their settings",
    },
    "reports": {
        "spam": "Spam (Ain't No Good)",
        "harassment": "Harassment or abuse towards others (No Way)",
        "language": "Rude, vulgar or offensive language (Watch yer mouth!)",
        "nsfw": "NSFW (Bad Stuff – You Know What I Mean)",
        "scam": "Scams, hacks, phishing or other shady mischief",
        "harm": "Threatenin' violence or real-world harm (Not Allowed)",
        "illegal": "Illegal activity (Against the Law!)",
        "suicide": "Self-harm/suicide (Reach Out for Help)",
        "age": "This lil' one’s too young to use Meower",
        "other": "Other (You Tell Us)",
    },
    "modals": {
        "report": "Report the Misbehavin’ Post",
        "blockword": "Blacklist a Word",
        "blockauser": "Block a User (Case Sensitive, Just Like the Wild West)",
        "blockuser": "Block that Rustler",
        "unblockuser": "Unblock that Rustler",
        "bgimage": "Background Image Trail Link",
        "blockedip": "IP Blocked (Whoa Nelly!)",
        "cleartokens": "Clear Tokens (Y’all Sure?)",
        "changepass": "Change Your Secret Key",
        "clearls": "Clear Localstorage? (You Betcha!)",
        "deleteacc": "Delete Account? (Are Ya Sure?)",
        "share": "Share This Roundup",
        "plugin": "Refresh Required – Let’s Giddy Up!",
        "shortcuts": "Shortcuts for Quick Travel",
        "copyuser": "Copied yer brand name to the clipboard!",
    },
    "profile": {
        "quote": "Quote",
        "persona": "Personalization (Make it Yer Own)",
        "profilecolor": "Profile Color (Choose Wisely)",
        "profilepic": "Profile Picture (Show Off)",
    },
    "chats": {
        "owner": "Owner of the Range",
        "members": "Fellow Trail Riders"
    }
}

const eris = {
    "language": "eris",
    "page_home": "home",
    "page_start": "start",
    "page_explore": "lame",
    "page_inbox": "annoyance",
    "page_settings": "settings",
    "meo_username": "usr",
    "meo_password": "pw",
    "meo_messagebox": "message box",
    "meo_goanywhere": "search something",
    "meo_welcome": "howdy",
    "meo_bridged": {
        "start": "lame",
        "title": "this post has been bridgeth"
    },
    "title_chats": "gcs",
    "title_live": "lc",
    "settings_general": "genereal",
    "settings_appearance": "themes",
    "settings_plugins": "plugins",
    "settings_languages": "langs",
    "general_sub": {
        "chat": "gc",
        "accessibility": "accessibility",
        "misc": "misc",
        "acc": "acc",
        "blockedusers": "u beeen blocked",
        "blockedwords": "bad words",
        "about": "about",
        "credits": "credits",
        "contrib": "contrib",
        "privacy": "privacy & safety",
    },
    "general_list": {
        "title": {
            "homepage": "i dont like the start page",
            "consolewarnings": "i know what i am doing",
            "blockedmessages": "get them away",
            "invtyping": "introvert mode",
            "imagewhitelist": "your ip address, who wants it",
            "censorwords": "censor bad words",
            "embeds": "free cookies, who wants it",
            "reducemotion": "less motion",
            "showpostbuttons": "always show post buttons",
            "underlinelinks": "always underline links",
            "magnify": "BIG TEXT",
            "entersend": "shift + enter to send",
            "hideimages": "hide images",
            "notifications": "HI CAN I ANNOY YOU",
            "widemode": "new desktop expERIcene",
            "discord": "upside down",
        },
        "desc": {
            "homepage": "i dont like the start page",
            "consolewarnings": "hides warning message from console",
            "blockedmessages": "no more console warnings",
            "invtyping": "other people wont know youre typing",
            "imagewhitelist": "give your ip to any website",
            "censorwords": "BAD WORD",
            "embeds": "i like tenor gifs tho",
            "reducemotion": "less moving effects",
            "showpostbuttons": "i like the post buttons(?)",
            "underlinelinks": "pretty self-explanatory",
            "magnify": "grandma mode",
            "entersend": "perfect for mobile devices",
            "hideimages": "its like every attachment is spoilered",
            "notifications": "give me notification",
            "widemode": "new thing please rate",
            "discord": "discord mode",
        }
    },
    "appearance_sub": {
        "theme": "theem",
        "spthemes": "special theems",
        "acthemes": "accessible theems",
        "ogthemes": "OG themees",
        "glthemes": "aero",
        "cstheme": "custom theem",
        "cscss": "custom CSS",
    },
    "plugins_sub": {
        "manage": "manage",
        "desc": "pls make ",
        "link": "plugins"
    },
    "languages_sub": {
        "title": "pick a lang any one",
        "desc": "please add",
        "link": "translations",
        "other": "silly languages"
    },
    "inbox_sub": {
        "desc": "this is where we annoy you",
    },
    "live_sub": {
        "desc": "chat history? no"
    },
    "login_sub": {
        "title": "login",
        "desc": "hi i made this",
        "oldpass": "old pw",
        "newpass": "new pw",
        "agreement": "legal shtuff",
    },
    "leave_sub": {
        "desc": "please stay",
        "end": "",
    },
    "action": {
        "logout": "logout",
        "login": "log in",
        "signup": "create account (mistake)",
        "search": "searchies",
        "mod": "ban people",
        "creategc": "make gc",
        "leavegc": "leave",
        "dmme": "dont dm me",
        "invite": "invite (mistake)",
        "gohome": "howome",
        "cleartokens": "sign out everywhere",
        "changepw": "change pw",
        "clearls": "reset",
        "deleteacc": "begone",
        "block": "you been blocked",
        "blockuser": "block someone",
        "blockword": "bad word",
        "run": "walk",
        "close": "close",
        "back": "go back",
        "opennewtab": "open in browser",
        "reply": "reply",
        "mention": "ping",
        "report": "mods ban this guy",
        "delete": "del taco",
        "edit": "oops",
        "share": "share",
        "comment": "comment",
        "nick": "nick",
        "create": "create",
        "reason": "reason",
        "sendreport": "send",
        "yes": "yeah",
        "confirm": "yes",
        "update": "update",
        "go": "stop",
        "apply": "apply",
        "savetheme": "save",
        "loadtheme": "load",
        "resetplugins": "END IT ALL",
        "favorite": "favourite",
        "download": "download",
        "add": "add",
        "adduser": "add someone (mistake)", // update
        "transfer": "make someone else owner (mistake)", // update
        "bug": "i found a problem", // update
        "datarequest": "i love collecting infomation", // update
        "discuss": "discuss", // update
    },
    "info": {
        "accexists": "someone already sniped that one",
        "invaliduser": "wrong username",
        "invalidpass": "dont tell me you forgot the password",
        "invalidcreds": "something went wrong",
        "accbanned": "YOU BEEN BANNED",
        "accdeleted": "deleterd",
        "conflict": "how did we get here",
        "unknown": "what happened",
        "chatremoved": "you left the chat",
        "passupdate": "someone changed your password",
        "editingpost": "editing",
        "reportsent": "sended",
        "blockedip": "you been IP BAN",
        "searchany": "search anything",
        "cleartokens": "this might log you out everywhere.",
        "clearls": "this might log you out.",
        "signup": "please read the tos",
        "tokenscleared": "time to log back in",
        "accscheduled": "account scheduled for deletion",
        "deletewarn": "It will be deleted FOREVER (a very long time!)",
        "changepwwarn": "whar",
        "tryagain": "something",
        "cleared": "cleared!",
        "plugin": "u need a restart",
    },
    "reports": {
        "spam": "annoying",
        "harassment": "being mean",
        "language": "bad words",
        "nsfw": "nsfw",
        "scam": "Scamming",
        "harm": "violence",
        "illegal": "ilelgal",
        "suicide": "suicide",
        "age": "under the age",
        "other": "other",
    },
    "modals": {
        "report": "mods",
        "blockword": "bad word",
        "blockauser": "block someone",
        "blockuser": "blocked",
        "unblockuser": "unblock",
        "bgimage": "g",
        "blockedip": "u been blokced",
        "cleartokens": "C",
        "changepass": "change pw",
        "clearls": "huh",
        "deleteacc": "NO DONT GO",
        "share": "share",
        "plugin": "refresh",
        "shortcuts": "shortcuts",
        "copyuser": "nice",
    },
    "profile": {
        "quote": "quote",
        "persona": "persona",
        "profilecolor": "colour",
        "profilepic": "pfp",
    },
    "chats": { // update
        "owner": "owner",
        "members": "members"
    }
}

if (localStorage.getItem("language")) {
    setlang(localStorage.getItem("language"));
} else {
    setlang("en");
}
